import { ROUTES, routeLabels } from './router.js';
import { subtaskProgress, taskView } from '../state/tasks.js';

const dailyRoutes = [ROUTES.DAILY, ROUTES.END_OF_DAY, ROUTES.MORNING_HUDDLE, ROUTES.TODAY];
const moreRoutes = [ROUTES.TASKS, ROUTES.ROADMAP, ROUTES.KPIS, ROUTES.ISSUES, ROUTES.MEETINGS, ROUTES.IMPROVEMENT, ROUTES.PLAYBOOKS, ROUTES.ANALYTICS, ROUTES.SETTINGS];
export function renderApp(root, route, tasks = []) { root.replaceChildren(); const shell = el('div', { className: 'app-layout' }); shell.append(sidebar(route), main(route, tasks), mobileNav(route), el('div', { id: 'toast-region', className: 'toast-region', role: 'status', 'aria-live': 'polite' }), el('div', { id: 'dialog-layer' })); root.append(shell); }
function sidebar(route) { const aside = el('aside', { className: 'sidebar', 'aria-label': 'Primary navigation' }); aside.append(el('a', { className: 'brand', href: '#daily', 'aria-label': 'TalentisOS daily home' }, 'Talentis', el('span', {}, 'OS')), el('p', { className: 'nav-heading' }, 'Daily rhythm'), navList(dailyRoutes, route), el('p', { className: 'nav-heading nav-heading--secondary' }, 'Leadership tools'), navList(moreRoutes, route)); return aside; }
function mobileNav(route) { const nav = el('nav', { className: 'mobile-nav', 'aria-label': 'Daily navigation' }); dailyRoutes.forEach(item => nav.append(navItem(item, route))); nav.append(el('a', { className: `nav-item ${moreRoutes.includes(route) ? 'is-active' : ''}`, href: '#tasks' }, icon('☰'), el('span', {}, 'More'))); return nav; }
function navList(routes, route) { const nav = el('nav', { className: 'nav-list' }); routes.forEach(item => nav.append(navItem(item, route))); return nav; }
function navItem(item, route) { return el('a', { className: `nav-item ${item === route ? 'is-active' : ''}`, href: `#${item}`, 'aria-current': item === route ? 'page' : undefined }, icon(routeIcon(item)), el('span', {}, routeLabels[item])); }
function main(route, tasks) { const main = el('main', { className: 'main-content', id: 'main-content', tabindex: '-1' }); main.append(route === ROUTES.DAILY ? dailyView() : route === ROUTES.TASKS ? tasksView(tasks) : route === ROUTES.SETTINGS ? settingsView() : placeholder(route)); return main; }
function tasksView(tasks) { const page = el('div', { className: 'page stack' }, pageHeader('Tasks', 'Capture once. Carry forward. Complete everywhere.')); const capture = el('form', { className: 'task-capture card', 'data-task-form': '' }, el('label', { className: 'visually-hidden', for: 'task-title' }, 'New task'), el('input', { id: 'task-title', name: 'title', required: '', maxlength: '500', placeholder: 'Capture a task…' }), el('input', { name: 'dueDate', type: 'date', 'aria-label': 'Due date' }), el('button', { className: 'button button--primary', type: 'submit' }, 'Add task')); const tabs = el('nav', { className: 'task-tabs', 'aria-label': 'Task views' }); const labels = { inbox: 'Inbox', today: 'Today', upcoming: 'Upcoming', anytime: 'Anytime', someday: 'Someday', flagged: 'Flagged', urgent: 'Urgent', completed: 'Completed' }; Object.entries(labels).forEach(([key, label]) => tabs.append(el('a', { href: `#tasks?view=${key}`, className: key === getTaskView() ? 'is-active' : '' }, label))); const view = getTaskView(); const list = taskView(tasks, view); const section = el('section', { className: 'task-list', 'aria-labelledby': 'task-list-heading' }, el('h2', { id: 'task-list-heading' }, labels[view])); if (!list.length) section.append(el('p', { className: 'empty-task secondary' }, emptyCopy(view))); else list.forEach(task => section.append(taskCard(task))); page.append(capture, tabs, section); return page; }
function getTaskView() { const params = new URLSearchParams(window.location.hash.split('?')[1]); const value = params.get('view'); return ['inbox','today','upcoming','anytime','someday','flagged','urgent','completed'].includes(value) ? value : 'inbox'; }
function emptyCopy(view) { return ({ today: 'Nothing due today.', flagged: 'No flagged tasks.', urgent: 'No urgent tasks.', completed: 'Completed work will appear here.' })[view] || 'Nothing to review here yet.'; }
function taskCard(task) {
  const progress = subtaskProgress(task);
  const card = el('article', { className: `task-card ${task.status === 'completed' ? 'is-completed' : ''}` });
  const action = el('button', { className: 'task-complete', type: 'button', 'data-task-action': task.status === 'completed' ? 'reopen' : 'complete', 'data-task-id': task.id, 'aria-label': task.status === 'completed' ? `Reopen ${task.title}` : `Complete ${task.title}` }, task.status === 'completed' ? '✓' : '○');
  const content = el('div', { className: 'task-card__content' }, el('h3', {}, task.title));
  const metadata = [];
  if (task.dueDate) metadata.push(`Due ${task.dueDate}`);
  if (task.priority !== 'normal') metadata.push(`${task.priority} priority`);
  if (task.urgent) metadata.push('Urgent'); if (task.flagged) metadata.push('Flagged'); if (task.blocked) metadata.push('Blocked'); if (task.waiting) metadata.push('Waiting');
  if (metadata.length) content.append(el('p', { className: 'task-meta' }, metadata.join(' · ')));
  if (progress.total) {
    content.append(el('p', { className: 'task-progress-copy' }, `${progress.completed} of ${progress.total}`));
    content.append(el('div', { className: 'progress', role: 'progressbar', 'aria-label': 'Subtask progress', 'aria-valuemin': '0', 'aria-valuemax': String(progress.total), 'aria-valuenow': String(progress.completed) }, el('span', { style: `width:${progress.percent}%` })));
    const subs = el('div', { className: 'subtask-list' });
    task.subtasks.forEach(sub => subs.append(el('div', { className: 'subtask' }, el('button', { type: 'button', 'data-task-action': sub.completed ? 'reopen-subtask' : 'complete-subtask', 'data-task-id': task.id, 'data-subtask-id': sub.id, 'aria-label': sub.completed ? 'Reopen subtask' : 'Complete subtask' }, sub.completed ? '✓' : '○'), el('span', { className: sub.completed ? 'done' : '' }, sub.title), el('button', { type: 'button', 'data-task-action': 'delete-subtask', 'data-task-id': task.id, 'data-subtask-id': sub.id, 'aria-label': 'Delete subtask' }, '×'))));
    content.append(subs);
  }
  const actions = el('div', { className: 'task-actions' }, smallAction('add-subtask', task, 'Subtask'), smallAction('toggle-urgent', task, task.urgent ? 'Not urgent' : 'Urgent'), smallAction('toggle-flagged', task, task.flagged ? 'Unflag' : 'Flag'), smallAction('toggle-blocked', task, task.blocked ? 'Unblock' : 'Block'), smallAction('toggle-waiting', task, task.waiting ? 'Resume' : 'Waiting'));
  card.append(action, content, actions); return card;
}
function smallAction(action, task, label) { return el('button', { className: 'task-action', type: 'button', 'data-task-action': action, 'data-task-id': task.id, 'data-value': String(action === 'toggle-urgent' ? task.urgent : action === 'toggle-flagged' ? task.flagged : action === 'toggle-blocked' ? task.blocked : task.waiting) }, label); }
function dailyView() { const page = el('div', { className: 'page stack' }, pageHeader('Your Daily Leadership Playbook', 'Lead the day before the day leads you.')); const flow = el('section', { className: 'daily-flow', 'aria-labelledby': 'daily-flow-heading' }, el('div', { className: 'section-intro' }, el('p', { className: 'eyebrow' }, 'Your rhythm'), el('h2', { id: 'daily-flow-heading' }, 'Prepare. Align. Execute.'))); const tiles = el('div', { className: 'flow-grid' }); [['01', 'End of Day', 'Close today with clarity, then carry only what matters.', ROUTES.END_OF_DAY], ['02', 'Morning Huddle', 'Start aligned on people, priorities and any blockers.', ROUTES.MORNING_HUDDLE], ['03', 'Today’s Work', 'Focus your leadership attention on the next right action.', ROUTES.TODAY]].forEach(([number, title, copy, route]) => tiles.append(el('a', { className: 'flow-card', href: `#${route}` }, el('span', { className: 'flow-number' }, number), el('h3', {}, title), el('p', {}, copy), el('span', { className: 'flow-link' }, 'Open →')))); flow.append(tiles); const attention = el('section', { className: 'section', 'aria-labelledby': 'attention-heading' }, el('div', { className: 'section-heading' }, el('p', { className: 'eyebrow' }, 'At a glance'), el('h2', { id: 'attention-heading' }, 'Leadership attention'))); const grid = el('div', { className: 'attention-grid' }); [['Top 3', 'Choose the three outcomes that make today count.'], ['Risks & blockers', 'Surface obstacles before they become urgent.'], ['Outstanding actions', 'Keep ownership and follow-through visible.'], ['KPI exceptions', 'Review what needs a leadership decision.']].forEach(([title, copy]) => grid.append(emptyTile(title, copy))); attention.append(grid); page.append(flow, attention); return page; }
function settingsView() { return el('div', { className: 'page stack' }, pageHeader('Settings', 'Your data stays on this device unless you choose to export it.'), el('section', { className: 'settings-card card', 'aria-labelledby': 'backup-heading' }, el('p', { className: 'eyebrow' }, 'Local data'), el('h2', { id: 'backup-heading' }, 'Backup & restore'), el('p', { className: 'secondary' }, 'Export a portable copy of your current tasks and preferences. Import replaces the local copy only after confirmation.'), el('div', { className: 'cluster' }, el('button', { className: 'button button--primary', type: 'button', 'data-action': 'export' }, 'Export data'), el('label', { className: 'button button--secondary file-button' }, 'Import data', el('input', { type: 'file', accept: 'application/json,.json', 'data-action': 'import', className: 'visually-hidden' })))), el('section', { className: 'card settings-card' }, el('p', { className: 'eyebrow' }, 'Application'), el('h2', {}, 'TalentisOS'), el('p', { className: 'secondary' }, 'Local-first leadership workspace · Schema version 2'))); }
function placeholder(route) { const label = routeLabels[route]; return el('div', { className: 'page stack' }, pageHeader(label, dailyRoutes.includes(route) ? 'This daily workflow will be ready in its dedicated phase.' : 'This leadership tool is prepared for a later, focused phase.'), el('section', { className: 'empty-state card' }, el('div', { className: 'empty-icon', 'aria-hidden': 'true' }, '○'), el('h2', {}, 'Nothing needs your attention here yet.'), el('p', { className: 'secondary' }, 'TalentisOS is keeping this space clear until the workflow is ready to support your day.'))); }
function pageHeader(title, description) { return el('header', { className: 'page-header' }, el('p', { className: 'eyebrow' }, 'TalentisOS'), el('h1', { id: 'page-title' }, title), el('p', { className: 'page-description' }, description)); }
function emptyTile(title, copy) { return el('article', { className: 'metric-tile' }, el('h3', {}, title), el('p', {}, copy), el('span', { className: 'empty-label' }, 'Nothing to review yet')); }
function routeIcon(route) { return ({ daily: '⌂', 'end-of-day': '◐', 'morning-huddle': '☀', today: '✓', tasks: '☷', roadmap: '↗', kpis: '◫', issues: '!', meetings: '◌', improvement: '↑', playbooks: '▤', analytics: '⌁', settings: '⚙' })[route] ?? '•'; }
function icon(value) { return el('span', { className: 'nav-icon', 'aria-hidden': 'true' }, value); }
function el(tag, attributes = {}, ...children) { const node = document.createElement(tag); for (const [key, value] of Object.entries(attributes)) { if (value === undefined) continue; if (key === 'className') node.className = value; else node.setAttribute(key, value); } children.flat().forEach(child => node.append(child instanceof Node ? child : document.createTextNode(String(child)))); return node; }
