import { ROUTES, routeLabels } from './router.js';
import { subtaskProgress, taskView } from '../state/tasks.js';
import { activeTop3TaskIds, nextWorkday } from '../state/end-of-day.js';
import { nextBestAction, roadmapProgress, stageProgress } from '../state/roadmap.js';

const dailyRoutes = [ROUTES.DAILY, ROUTES.END_OF_DAY, ROUTES.MORNING_HUDDLE, ROUTES.TODAY];
const moreRoutes = [ROUTES.TASKS, ROUTES.ROADMAP, ROUTES.KPIS, ROUTES.ISSUES, ROUTES.MEETINGS, ROUTES.IMPROVEMENT, ROUTES.PLAYBOOKS, ROUTES.ANALYTICS, ROUTES.SETTINGS];
export function renderApp(root, route, tasks = [], endOfDay = null, today = localDate(), eodHistory = [], huddle = null, todaysWork = null, roadmap = null, scorecard = [], dashboard = null) { root.replaceChildren(); const shell = el('div', { className: 'app-layout' }); shell.append(sidebar(route), main(route, tasks, endOfDay, today, eodHistory, huddle, todaysWork, roadmap, scorecard, dashboard), mobileNav(route), el('div', { id: 'toast-region', className: 'toast-region', role: 'status', 'aria-live': 'polite' }), el('div', { id: 'dialog-layer' })); root.append(shell); }
function sidebar(route) { const aside = el('aside', { className: 'sidebar', 'aria-label': 'Primary navigation' }); aside.append(el('a', { className: 'brand', href: '#daily', 'aria-label': 'TalentisOS daily home' }, 'Talentis', el('span', {}, 'OS')), el('p', { className: 'nav-heading' }, 'Daily rhythm'), navList(dailyRoutes, route), el('p', { className: 'nav-heading nav-heading--secondary' }, 'Leadership tools'), navList(moreRoutes, route)); return aside; }
function mobileNav(route) { const nav = el('nav', { className: 'mobile-nav', 'aria-label': 'Daily navigation' }); dailyRoutes.forEach(item => nav.append(navItem(item, route))); nav.append(el('a', { className: `nav-item ${moreRoutes.includes(route) ? 'is-active' : ''}`, href: '#tasks' }, icon('☰'), el('span', {}, 'More'))); return nav; }
function navList(routes, route) { const nav = el('nav', { className: 'nav-list' }); routes.forEach(item => nav.append(navItem(item, route))); return nav; }
function navItem(item, route) { return el('a', { className: `nav-item ${item === route ? 'is-active' : ''}`, href: `#${item}`, 'aria-current': item === route ? 'page' : undefined }, icon(routeIcon(item)), el('span', {}, routeLabels[item])); }
function main(route, tasks, endOfDay, today, eodHistory, huddle, todaysWork, roadmap, scorecard, dashboard) { const main = el('main', { className: 'main-content', id: 'main-content', tabindex: '-1' }); main.append(route === ROUTES.DAILY ? dashboardView(dashboard) : route === ROUTES.END_OF_DAY ? endOfDayView(tasks, endOfDay, today, eodHistory) : route === ROUTES.MORNING_HUDDLE ? morningHuddleView(huddle, today) : route === ROUTES.TODAY ? todaysWorkView(todaysWork, tasks, today) : route === ROUTES.TASKS ? tasksView(tasks) : route === ROUTES.ROADMAP ? roadmapView(roadmap) : route === ROUTES.KPIS ? scorecardView(scorecard, tasks) : route === ROUTES.SETTINGS ? settingsView() : placeholder(route)); return main; }
function dashboardView(data) { const d = data || { action: { title: 'You are aligned for today', reason: 'No current exception needs action.', href: '#today', label: 'View Today’s Work' }, rhythm: {}, taskAttention: [], top: [], kpiExceptions: [], huddleItems: [], completed: [] }; const page = el('div', { className: 'page stack dashboard-page' }, pageHeader('Home', 'See what needs attention, then take the next useful leadership action.'));
  page.append(el('section', { className: 'dashboard-next card', 'aria-labelledby': 'dashboard-next' }, el('p', { className: 'eyebrow' }, 'Next Best Action'), el('h2', { id: 'dashboard-next' }, d.action.title), el('p', { className: 'secondary' }, d.action.reason), el('a', { className: 'button button--primary', href: d.action.href }, d.action.label)));
  const rhythm = el('section', { 'aria-labelledby': 'daily-rhythm-heading' }, el('div', { className: 'section-intro' }, el('p', { className: 'eyebrow' }, 'Daily Rhythm'), el('h2', { id: 'daily-rhythm-heading' }, 'Keep the leadership loop moving'))); const rhythmGrid = el('div', { className: 'dashboard-rhythm' }); [['End of Day', d.rhythm.endOfDay, '#end-of-day'], ['Morning Huddle', d.rhythm.huddle, '#morning-huddle'], ['Today’s Work', d.rhythm.today, '#today']].forEach(([title, state, href]) => rhythmGrid.append(el('a', { className: 'dashboard-rhythm-card', href }, el('h3', {}, title), el('p', {}, state), el('span', {}, 'Open →')))); rhythm.append(rhythmGrid); page.append(rhythm);
  page.append(dashboardList('Tasks needing attention', d.taskAttention, task => task.title, '#tasks', 'No overdue, urgent, blocked, or waiting tasks.'), dashboardList('Top 3', d.top, entry => entry.task.title, '#today', 'No Top 3 priorities aligned yet.'), dashboardList('KPI exceptions', d.kpiExceptions, item => `${item.kpi.name} — ${item.status.replace('-', ' ')}`, '#kpis', 'No amber or red KPI exceptions.'), dashboardList('Huddle attention', d.huddleAttention, item => item.title, '#morning-huddle', 'No current Huddle commitments, risks, customer issues, or decisions.'), dashboardList('Completed today', d.completed, task => task.title, '#today', 'Momentum will appear here as canonical tasks are completed.'));
  return page; }
function dashboardList(title, items, label, href, empty) { const shown = items.slice(0, 3); return el('section', { className: 'dashboard-section card' }, el('div', { className: 'dashboard-section-head' }, el('h2', {}, title), el('a', { href }, 'View all')), shown.length ? el('ul', { className: 'dashboard-list' }, ...shown.map(item => el('li', {}, label(item)))) : el('p', { className: 'secondary' }, empty)); }
function roadmapView(roadmap) {
  const progress = roadmapProgress(roadmap); const next = nextBestAction(roadmap); const page = el('div', { className: 'page stack roadmap-page' }, pageHeader('Leadership Roadmap', 'A calm 30–60–90 guide for your leadership transition.'));
  const overview = el('section', { className: 'roadmap-overview card' }, el('div', {}, el('p', { className: 'eyebrow' }, 'Your progress'), el('h2', {}, `${progress.completed} of ${progress.total} milestones complete`), el('p', { className: 'secondary' }, `${progress.percent}% of your roadmap is complete.`)), el('div', { className: 'progress roadmap-progress', role: 'progressbar', 'aria-label': 'Leadership roadmap progress', 'aria-valuemin': '0', 'aria-valuemax': String(progress.total), 'aria-valuenow': String(progress.completed) }, el('span', { style: `width:${progress.percent}%` })));
  page.append(overview);
  if (next) page.append(el('section', { className: 'roadmap-next card', 'aria-labelledby': 'next-best-action-heading' }, el('p', { className: 'eyebrow' }, 'Next Best Action'), el('h2', { id: 'next-best-action-heading' }, next.title), el('p', { className: 'secondary' }, next.outcome), roadmapAction(next)));
  else page.append(el('section', { className: 'roadmap-next card' }, el('p', { className: 'eyebrow' }, 'Roadmap complete'), el('h2', {}, 'Your first 90 days are complete.'), el('p', { className: 'secondary' }, 'Use the review to set the next priorities.')));
  [[30, '30 — Learn & Stabilise'], [60, '60 — Align & Improve'], [90, '90 — Scale & Lead']].forEach(([stage, label]) => { const stats = stageProgress(roadmap, stage); const section = el('section', { className: 'roadmap-stage', 'aria-labelledby': `roadmap-stage-${stage}` }, el('div', { className: 'section-heading roadmap-stage-heading' }, el('div', {}, el('p', { className: 'eyebrow' }, label), el('h2', { id: `roadmap-stage-${stage}` }, `${stats.completed} of ${stats.total} complete`)))); const list = el('div', { className: 'roadmap-list' }); (roadmap?.milestones || []).filter(milestone => milestone.stage === stage).forEach(milestone => list.append(el('article', { className: `roadmap-milestone ${milestone.status === 'completed' ? 'is-completed' : ''}` }, el('div', { className: 'roadmap-milestone-copy' }, el('h3', {}, milestone.title), el('p', {}, milestone.outcome)), roadmapAction(milestone)))); section.append(list); page.append(section); }); return page;
}
function roadmapAction(milestone) { const complete = milestone.status !== 'completed'; return el('button', { type: 'button', className: complete ? 'button button--primary roadmap-action' : 'button button--secondary roadmap-action', 'data-roadmap-action': complete ? 'complete' : 'reopen', 'data-milestone-id': milestone.id, 'aria-label': `${complete ? 'Complete' : 'Reopen'} ${milestone.title}` }, complete ? 'Mark complete' : 'Reopen'); }
function todaysWorkView(work, tasks, date) {
  const snapshot = work || { top: [], attention: [], today: [], completed: [], progress: { total: 0, completed: 0 } };
  const { total, completed } = snapshot.progress; const percent = total ? Math.round(completed / total * 100) : 0;
  const page = el('div', { className: 'page stack today-page' }, pageHeader('Today’s Work', 'Lead the day before the day leads you.'));
  page.append(el('section', { className: 'today-overview card' }, el('div', {}, el('p', { className: 'eyebrow' }, formatWorkday(date)), el('h2', {}, total ? `${completed} of ${total} complete` : 'Nothing aligned yet'), el('p', { className: 'secondary' }, total ? `${percent}% of today’s relevant work is complete.` : 'Start with the Morning Huddle or add work for today.')), el('div', { className: 'progress today-progress', 'aria-label': `${percent}% complete` }, el('span', { style: `width:${percent}%` }))));
  const capture = el('form', { className: 'today-capture card', 'data-today-capture-form': '' }, el('label', { className: 'visually-hidden', for: 'today-title' }, 'New task for today'), el('input', { id: 'today-title', name: 'title', required: '', maxlength: '500', placeholder: 'Capture work for today…' }), el('button', { type: 'submit', className: 'button button--primary' }, 'Add to Today'));
  page.append(capture, todaySection('Top 3', 'Primary focus for the day.', snapshot.top, 'Choose up to three priorities in the Morning Huddle.'), todaySection('Needs Attention', 'Exceptions that need deliberate action.', snapshot.attention, 'No urgent, overdue, blocked, or waiting work.'), todaySection('Today', 'Other work ready for execution.', snapshot.today, 'Add an existing task from Tasks or capture work above.'));
  const complete = el('details', { className: 'card today-completed', open: false }, el('summary', {}, el('span', {}, 'Completed Today'), el('small', {}, `${snapshot.completed.length} complete`)));
  complete.append(snapshot.completed.length ? el('div', { className: 'today-list' }, ...snapshot.completed.map(todayTask)) : el('p', { className: 'secondary' }, total ? 'No work completed today yet.' : 'Today’s commitments are complete.'));
  page.append(complete);
  const available = tasks.filter(task => task.status === 'open' && !task.someday && ![...snapshot.top, ...snapshot.attention, ...snapshot.today].some(entry => entry.task.id === task.id));
  if (available.length) page.append(el('details', { className: 'card today-add-existing' }, el('summary', {}, el('span', {}, 'Add existing task'), el('small', {}, 'Reference it without copying')), el('div', { className: 'today-existing-list' }, ...available.slice(0, 12).map(task => el('div', { className: 'today-existing' }, el('span', {}, task.title), el('button', { type: 'button', className: 'task-action', 'data-today-add': '', 'data-task-id': task.id }, 'Add to Today'))))));
  return page;
}
function todaySection(title, copy, entries, empty) { const section = el('section', { className: 'today-section' }, el('div', { className: 'section-intro' }, el('h2', {}, title), el('p', { className: 'secondary' }, copy))); section.append(entries.length ? el('div', { className: 'today-list' }, ...entries.map(todayTask)) : el('p', { className: 'secondary today-empty' }, empty)); return section; }
function todayTask(entry) { const { task, reasons } = entry; const progress = subtaskProgress(task); const badges = [...reasons, task.priority !== 'normal' ? `${task.priority} priority` : null].filter(Boolean); const action = task.status === 'completed' ? 'reopen' : 'complete'; return el('article', { className: `today-task ${task.status === 'completed' ? 'is-completed' : ''}` }, el('button', { type: 'button', className: 'task-complete', 'data-task-action': action, 'data-task-id': task.id, 'aria-label': action === 'complete' ? `Complete ${task.title}` : `Reopen ${task.title}` }, action === 'complete' ? '○' : '✓'), el('div', { className: 'today-task-content' }, el('h3', {}, task.title), badges.length ? el('div', { className: 'today-badges' }, ...badges.map(label => el('span', { className: `today-badge ${label === 'Overdue' ? 'is-overdue' : ''}` }, label))) : '', progress.total ? el('div', {}, el('p', { className: 'task-progress-copy' }, `${progress.completed} of ${progress.total} subtasks`), el('div', { className: 'progress' }, el('span', { style: `width:${progress.percent}%` }))) : ''), el('div', { className: 'task-actions' }, el('button', { type: 'button', className: 'task-action', 'data-task-action': 'add-subtask', 'data-task-id': task.id }, 'Subtask'), el('button', { type: 'button', className: 'task-action', 'data-task-action': 'edit', 'data-task-id': task.id }, 'Details'))); }
function endOfDayView(tasks, record, today, history = []) {
  const destination = record?.nextWorkday || nextWorkday(today); const selected = new Set(record?.outstandingTaskIds || record?.taskIds || []); const top3 = new Set(activeTop3TaskIds(record?.top3TaskIds, tasks));
  const completed = tasks.filter(task => task.status === 'completed' && task.completedAt?.slice(0, 10) === today);
  const relevant = tasks.filter(task => task.status === 'open' && !task.someday && (task.dueDate === today || task.dueDate < today || task.urgent || task.flagged || task.blocked || task.waiting || selected.has(task.id))).sort((a, b) => (b.urgent - a.urgent) || (a.dueDate || '9999').localeCompare(b.dueDate || '9999'));
  const candidateTasks = tasks.filter(task => task.status === 'open' && !task.someday).sort((a, b) => (b.urgent - a.urgent) || (a.dueDate || '9999').localeCompare(b.dueDate || '9999'));
  const page = el('div', { className: 'page stack' }, pageHeader('End of Day', record?.status === 'complete' ? `Complete. Preparing ${formatWorkday(destination)}.` : `Close the day. Prepare ${formatWorkday(destination)}.`));
  page.append(el('p', { className: 'eyebrow' }, `Status: ${record?.status?.replace('-', ' ') || 'Not started'}`), eodTiles(completed, relevant, record, top3));
  const form = el('form', { className: 'eod-form', 'data-eod-form': '' });
  form.append(eodSection('completed', 'Completed', `${completed.length} completed today`, completed.length ? taskSummary(completed) : el('p', { className: 'secondary' }, 'Nothing completed yet today.')));
  const capture = el('div', { className: 'stack' }, field('wins', 'What mattered today?', record?.wins || '', 'A short note about work completed or progress made.'), field('reflection', 'Close-out note', record?.reflection || '', 'What should you remember when you return?'));
  form.append(eodSection('capture', 'Capture', 'A quick close-out', capture));
  const carry = el('div', { className: 'eod-task-list' });
  if (relevant.length) { carry.append(el('button', { type: 'button', className: 'button button--secondary', 'data-eod-select-all': '' }, 'Add all outstanding')); relevant.forEach(task => carry.append(taskCheckbox(task, 'taskIds', selected.has(task.id)))); } else carry.append(el('p', { className: 'secondary' }, 'Nothing needs carrying forward.'));
  form.append(eodSection('outstanding', 'Outstanding', `${relevant.length} relevant open task${relevant.length === 1 ? '' : 's'}`, carry));
  const blocked = relevant.filter(task => task.blocked || task.waiting); form.append(eodSection('blocked', 'Blocked / Waiting', blocked.length ? taskSummary(blocked) : el('p', { className: 'secondary' }, 'No blocked or waiting work needs review.')));
  const top = el('div', { className: 'eod-task-list' }, el('p', { className: 'secondary' }, 'Choose up to three outcomes for the next workday.'));
  candidateTasks.forEach(task => top.append(taskCheckbox(task, 'top3TaskIds', top3.has(task.id), 'data-top3-option'))); form.append(eodSection('top3', "Tomorrow's Top 3", `${top3.size}/3 selected`, top));
  const actions = el('div', { className: 'cluster' }, el('button', { type: 'submit', name: 'intent', value: 'save', className: 'button button--secondary' }, 'Save progress'), el('button', { type: 'submit', name: 'intent', value: 'close', className: 'button button--primary' }, record?.status === 'complete' ? 'Update End of Day' : `Complete End of Day`));
  form.append(actions); if (record?.status === 'complete') page.append(el('button', { type: 'button', className: 'button button--secondary', 'data-eod-action': 'reopen' }, 'Reopen for correction'));
  const past = history.filter(item => (item.workDate || item.date) !== today).slice(0, 5); const historySection = el('section', { className: 'card eod-card' }, el('h2', {}, 'Recent End of Day records')); historySection.append(past.length ? el('ul', { className: 'eod-entry-list' }, ...past.map(item => el('li', {}, `${item.workDate || item.date} — ${item.status || 'complete'} · ${item.top3TaskIds?.length || 0} Top 3`))) : el('p', { className: 'secondary' }, 'Previous End of Day records will appear here.'));
  page.append(form, entrySection('risks', 'Risks / Critical', record?.risks), entrySection('customerIssues', 'Customer / Service Issues', record?.customerIssues), entrySection('decisions', 'Decisions', record?.decisions), entrySection('handovers', 'Handovers', record?.handovers), entrySection('improvements', 'Improvements / Lessons', record?.improvements), historySection); return page;
}
const statusMeta = { 'on-track': ['🟢', 'On Track'], 'at-risk': ['🟠', 'At Risk'], 'off-track': ['🔴', 'Off Track'], 'not-reported': ['⚪', 'Not Reported'] };
function scorecardView(snapshot, tasks) {
  const page = el('div', { className: 'page stack scorecard-page' }, pageHeader('Scorecard', 'Start with exceptions. Report the measure, then make the next action clear.'));
  const count = status => snapshot.filter(item => item.status === status).length;
  page.append(el('section', { className: 'scorecard-summary', 'aria-label': 'KPI status summary' }, ...['on-track', 'at-risk', 'off-track', 'not-reported'].map(status => { const [icon, label] = statusMeta[status]; return el('div', { className: `scorecard-tile is-${status}` }, el('strong', {}, `${icon} ${count(status)}`), el('span', {}, label)); })));
  const exceptions = snapshot.filter(item => item.status === 'off-track' || item.status === 'at-risk');
  const exceptionSection = el('section', { className: 'scorecard-section' }, el('div', { className: 'section-intro' }, el('p', { className: 'eyebrow' }, 'Act first'), el('h2', {}, 'Exceptions'), el('p', { className: 'secondary' }, 'Red measures require an open canonical corrective-action task; amber measures may link one.')));
  exceptionSection.append(exceptions.length ? el('div', { className: 'scorecard-list' }, ...exceptions.map(item => kpiCard(item, tasks))) : el('p', { className: 'today-empty secondary' }, 'No reported KPI exceptions. Add a KPI or report this period’s actual to keep the scorecard useful.'));
  page.append(exceptionSection);
  const all = el('details', { className: 'card scorecard-all', open: !snapshot.length }, el('summary', {}, el('span', {}, 'All KPIs'), el('small', {}, `${snapshot.length} measure${snapshot.length === 1 ? '' : 's'}`)));
  all.append(snapshot.length ? el('div', { className: 'scorecard-list' }, ...snapshot.filter(item => !exceptions.includes(item)).map(item => kpiCard(item, tasks))) : el('p', { className: 'secondary' }, 'No KPIs yet. Create your first measure below.'));
  page.append(all, kpiForm()); return page;
}
function kpiCard(item, tasks) {
  const { kpi, entry, periodKey, status, trend, entries, corrective } = item; const [symbol, label] = statusMeta[status];
  const card = el('article', { className: `kpi-card is-${status}` }, el('div', { className: 'kpi-card-head' }, el('div', {}, el('p', { className: 'eyebrow' }, `${symbol} ${label}`), el('h3', {}, kpi.name), el('p', { className: 'secondary' }, `${kpi.ownerRole} · ${kpi.frequency} · ${kpi.unit}`)), el('span', { className: 'kpi-trend', 'aria-label': `Trend: ${trend}` }, trend === 'up' ? '↑ Rising' : trend === 'down' ? '↓ Falling' : trend === 'steady' ? '→ Steady' : '— History needed')));
  card.append(el('p', { className: 'kpi-context' }, entry ? `Actual ${entry.actual} ${kpi.unit} · period ${periodKey}` : `No actual reported for ${periodKey}.`), el('p', { className: 'secondary' }, thresholdCopy(kpi)));
  const report = el('form', { className: 'kpi-entry-form', 'data-kpi-entry-form': '' }, el('input', { type: 'hidden', name: 'kpiId', value: kpi.id }), el('input', { type: 'hidden', name: 'periodKey', value: periodKey }), el('label', { className: 'visually-hidden' }, `Actual for ${kpi.name}`, el('input', { name: 'actual', type: 'number', step: 'any', required: '', value: entry?.actual ?? '', placeholder: 'Actual' })), el('input', { name: 'notes', maxlength: '500', value: entry?.notes ?? '', placeholder: 'Optional reporting note', 'aria-label': `Reporting note for ${kpi.name}` }), el('button', { className: 'button button--secondary', type: 'submit' }, entry ? 'Update actual' : 'Report actual'));
  card.append(report);
  const linked = corrective.linked; const actionCopy = corrective.required ? corrective.actioned ? 'Corrective action linked.' : 'Corrective action required.' : linked.length ? 'Optional corrective action linked.' : '';
  if (corrective.required || linked.length) { const available = tasks.filter(task => task.status === 'open' && !kpi.linkedTaskIds.includes(task.id)); const actions = [el('p', { className: corrective.actioned ? 'secondary' : 'kpi-required' }, actionCopy), ...linked.map(task => el('span', { className: 'kpi-task-ref' }, `${task.status === 'open' ? 'Open' : 'Complete'}: ${task.title}`)), el('button', { type: 'button', className: 'task-action', 'data-kpi-action': 'create-corrective', 'data-kpi-id': kpi.id }, 'Create canonical task')]; if (available.length) actions.push(el('select', { 'data-kpi-task-select': kpi.id, 'aria-label': `Open task to link to ${kpi.name}` }, el('option', { value: '' }, 'Link an open task…'), ...available.map(task => el('option', { value: task.id }, task.title))), el('button', { type: 'button', className: 'task-action', 'data-kpi-action': 'link-task', 'data-kpi-id': kpi.id }, 'Link task')); card.append(el('div', { className: 'kpi-actions' }, actions)); }
  const history = entries.slice(0, 4).map(value => `${value.periodKey}: ${value.actual}`).join(' · '); if (history) card.append(el('p', { className: 'kpi-history secondary' }, `Recent history: ${history}`)); return card;
}
function thresholdCopy(kpi) { const format = range => kpi.direction === 'higher' ? range.max : kpi.direction === 'lower' ? range.min : `${range.min}–${range.max}`; return `Target ${format(kpi.target)} · warning ${format(kpi.warning)} · off track ${format(kpi.offTrack)}.`; }
function kpiForm() { const form = el('form', { className: 'card kpi-form', 'data-kpi-form': '' }, el('p', { className: 'eyebrow' }, 'New measure'), el('h2', {}, 'Create a KPI'), el('p', { className: 'secondary' }, 'Use role or function ownership only. For higher/lower measures, place target closest to success, then warning, then off track. Within-range limits widen outward.'), el('label', {}, 'Optional editable template', el('select', { name: 'template' }, el('option', { value: '' }, 'Start from a blank KPI'), el('option', { value: '0' }, 'Customer response time'), el('option', { value: '1' }, 'On-time delivery / completion'), el('option', { value: '2' }, 'Rework / error rate'), el('option', { value: '3' }, 'Customer issues resolved within target'), el('option', { value: '4' }, 'Plan adherence'))));
  [['name', 'KPI name', 'text'], ['purpose', 'Purpose', 'text'], ['ownerRole', 'Owner role or function', 'text'], ['formula', 'Formula or data source', 'text'], ['unit', 'Unit', 'text']].forEach(([name, label, type]) => form.append(el('label', {}, label, el('input', { name, type, maxlength: '500' }))));
  const settings = el('div', { className: 'kpi-settings' }, el('label', {}, 'Frequency', el('select', { name: 'frequency' }, ...['daily', 'weekly', 'monthly', 'quarterly'].map(value => el('option', { value, selected: value === 'monthly' ? '' : undefined }, value[0].toUpperCase() + value.slice(1))))), el('label', {}, 'Direction', el('select', { name: 'direction' }, el('option', { value: 'higher' }, 'Higher is better'), el('option', { value: 'lower' }, 'Lower is better'), el('option', { value: 'within-range' }, 'Within range')))); form.append(settings);
  const thresholds = el('div', { className: 'kpi-thresholds' });
  ['target', 'warning', 'offTrack'].forEach(key => {
    thresholds.append(el('fieldset', {},
      el('legend', {}, key === 'offTrack' ? 'Off track' : key[0].toUpperCase() + key.slice(1)),
      el('label', {}, 'Minimum', el('input', { name: `${key}Min`, type: 'number', step: 'any', required: '' })),
      el('label', {}, 'Maximum', el('input', { name: `${key}Max`, type: 'number', step: 'any', required: '' }))
    ));
  });
  form.append(thresholds, el('button', { className: 'button button--primary', type: 'submit' }, 'Create KPI')); return form; }
function morningHuddleView(snapshot, today) {
  if (!snapshot) return placeholder(ROUTES.MORNING_HUDDLE);
  const { huddle, carryovers, top3, blockers, commitments, candidates, sourceFound, kpiExceptions = [] } = snapshot;
  const page = el('div', { className: 'page stack huddle-page' }, pageHeader('Morning Huddle', `${formatWorkday(today)} · ${huddle.status.replace('-', ' ')}`));
  const summary = [['Carryovers', carryovers.length], ['Top 3', top3.length], ['Blockers', blockers.length], ['Customer issues', huddle.customerIssues.length], ['Commitments', commitments.length]];
  page.append(el('p', { className: 'secondary' }, sourceFound ? `Prepared from End of Day ${huddle.sourceEodDate}. Review, align, commit.` : 'No prior End of Day was found. You can still align the day.'), el('section', { className: 'huddle-tiles', 'aria-label': 'Huddle overview' }, ...summary.map(([label, count]) => el('div', { className: 'huddle-tile' }, el('strong', {}, String(count)), el('span', {}, label)))));
  page.append(huddleTaskSection('Carryovers', 'What still needs attention?', carryovers, true), top3Section(top3, candidates), huddleTaskSection('Risks & Blockers', 'What could stop us?', blockers), kpiExceptionsSection(kpiExceptions), huddleEntries('Customer / Service Issues', 'Who needs attention?', huddle.customerIssues), huddleEntries('Resources & Support', 'What support is needed?', huddle.resourceSupportItems, 'resourceSupportItems'), huddleEntries('Decisions', 'What needs deciding?', huddle.decisions, 'decisions'), commitmentsSection(commitments), huddleEntries('Recognition', 'What should we acknowledge?', huddle.recognitionItems, 'recognitionItems'));
  const quick = el('section', { className: 'card huddle-card' }, el('h2', {}, 'New action'), el('p', { className: 'secondary' }, 'Create one canonical task and add it to today’s commitments.'), el('form', { className: 'huddle-action-form', 'data-huddle-action-form': '' }, el('input', { name: 'title', required: '', maxlength: '500', placeholder: 'What will be done?' }), el('input', { name: 'dueDate', type: 'date', 'aria-label': 'Due date' }), el('select', { name: 'priority', 'aria-label': 'Priority' }, el('option', { value: 'normal' }, 'Normal'), el('option', { value: 'high' }, 'High'), el('option', { value: 'low' }, 'Low')), el('button', { type: 'submit', className: 'button button--primary' }, 'Add commitment')));
  const action = huddle.status === 'completed' ? el('button', { type: 'button', className: 'button button--secondary', 'data-huddle-action': 'reopen-huddle' }, 'Reopen Huddle') : el('button', { type: 'button', className: 'button button--primary', 'data-huddle-action': 'complete-huddle' }, 'Complete Huddle');
  page.append(quick, el('section', { className: 'huddle-completion card' }, el('h2', {}, huddle.status === 'completed' ? 'Huddle complete' : 'Ready to align?'), el('p', { className: 'secondary' }, `${top3.length} Top 3 · ${blockers.length} blocker${blockers.length === 1 ? '' : 's'} · ${commitments.length} commitment${commitments.length === 1 ? '' : 's'}`), action)); return page;
}
function kpiExceptionsSection(exceptions) { const body = el('div', { className: 'huddle-task-list' }); if (exceptions.length) exceptions.forEach(item => { const [symbol, label] = statusMeta[item.status]; body.append(el('article', { className: 'huddle-task' }, el('div', {}, el('h3', {}, `${symbol} ${item.kpi.name}`), el('p', { className: 'task-meta' }, `${label} · ${item.entry?.actual ?? 'No actual'} ${item.kpi.unit}`), el('p', { className: 'secondary' }, item.corrective.linked.length ? item.corrective.linked.map(task => `${task.status === 'open' ? 'Open' : 'Complete'}: ${task.title}`).join(' · ') : item.status === 'off-track' ? 'Corrective action required — open Scorecard to create or link one.' : 'No linked action.')))); }); else body.append(el('p', { className: 'secondary' }, 'No current-period KPI exceptions.')); return el('section', { className: 'card huddle-card' }, el('h2', {}, 'KPI exceptions'), el('p', { className: 'secondary' }, 'Current scorecard exceptions and their canonical action references.'), body); }
function huddleTaskSection(title, prompt, tasks, removable = false) { const body = el('div', { className: 'huddle-task-list' }); if (tasks.length) tasks.forEach(task => body.append(huddleTask(task, removable))); else body.append(el('p', { className: 'secondary' }, title === 'Carryovers' ? 'Nothing was deliberately carried forward.' : 'No exceptions need attention.')); return el('section', { className: 'card huddle-card' }, el('h2', {}, title), el('p', { className: 'secondary' }, prompt), body); }
function huddleTask(task, removable = false) { const progress = subtaskProgress(task); const meta = [task.dueDate ? `Due ${task.dueDate}` : null, task.dueDate && task.dueDate < localDate() ? 'Overdue' : null, task.priority !== 'normal' ? `${task.priority} priority` : null, task.urgent ? 'Urgent' : null, task.blocked ? 'Blocked' : null, task.waiting ? 'Waiting' : null, task.carryCount ? `Carried ${task.carryCount}×` : null].filter(Boolean); const actions = [el('button', { type: 'button', className: 'task-complete', 'data-huddle-action': task.status === 'completed' ? 'reopen-task' : 'complete', 'data-task-id': task.id, 'aria-label': task.status === 'completed' ? `Reopen ${task.title}` : `Complete ${task.title}` }, task.status === 'completed' ? '✓' : '○')]; if (removable) actions.push(el('button', { type: 'button', className: 'task-action', 'data-huddle-action': 'remove', 'data-task-id': task.id }, 'Remove')); return el('article', { className: `huddle-task ${task.status === 'completed' ? 'is-completed' : ''}` }, ...actions, el('div', {}, el('h3', {}, task.title), meta.length ? el('p', { className: 'task-meta' }, meta.join(' · ')) : '', progress.total ? el('p', { className: 'task-progress-copy' }, `${progress.completed} of ${progress.total}`) : ''));
}
function top3Section(top3, candidates) { const selected = new Set(top3.map(task => task.id)); const form = el('form', { className: 'huddle-top3', 'data-huddle-top3-form': '' }); candidates.filter(task => selected.has(task.id) || task.status === 'open').forEach(task => { const label = el('label', { className: 'eod-task-option' }); const input = el('input', { type: 'checkbox', name: 'top3TaskIds', value: task.id }); input.checked = selected.has(task.id); label.append(input, el('span', {}, el('strong', {}, `${selected.has(task.id) ? `${top3.findIndex(item => item.id === task.id) + 1}. ` : ''}${task.title}`), el('small', {}, task.status === 'completed' ? 'Completed' : eodTaskMeta(task)))); form.append(label); }); form.append(el('button', { type: 'submit', className: 'button button--primary' }, 'Save Top 3')); return el('section', { className: 'card huddle-card' }, el('h2', {}, "Today’s Top 3"), el('p', { className: 'secondary' }, 'What matters most today? Choose no more than three.'), form); }
function commitmentsSection(tasks) { const body = el('div', { className: 'huddle-task-list' }); if (tasks.length) tasks.forEach(task => body.append(el('article', { className: `huddle-task ${task.status === 'completed' ? 'is-completed' : ''}` }, el('button', { type: 'button', className: 'task-complete', 'data-huddle-action': task.status === 'completed' ? 'reopen-task' : 'complete', 'data-task-id': task.id }, task.status === 'completed' ? '✓' : '○'), el('div', {}, el('h3', {}, task.title), el('p', { className: 'task-meta' }, 'Canonical commitment')), el('button', { type: 'button', className: 'task-action', 'data-huddle-action': 'uncommit', 'data-task-id': task.id }, 'Remove')))); else body.append(el('p', { className: 'secondary' }, 'Add actions as clear commitments.')); return el('section', { className: 'card huddle-card' }, el('h2', {}, 'Commitments / Actions'), el('p', { className: 'secondary' }, 'Who is doing what?'), body); }
function huddleEntries(title, prompt, values, section) { const body = el('div', { className: 'huddle-entry-body' }); if (values.length) body.append(el('ul', { className: 'eod-entry-list' }, ...values.map(value => el('li', {}, el('strong', {}, value.title), value.note ? ` — ${value.note}` : '')))); else body.append(el('p', { className: 'secondary' }, title === 'Customer / Service Issues' ? 'No customer issues captured.' : 'Nothing captured yet.')); if (section) body.append(el('form', { className: 'huddle-entry-form', 'data-huddle-entry-form': '' }, el('input', { type: 'hidden', name: 'section', value: section }), el('input', { name: 'title', required: '', maxlength: '240', placeholder: `Add ${title.toLowerCase()}…`, 'aria-label': `Add ${title}` }), el('input', { name: 'note', maxlength: '1000', placeholder: 'Optional context', 'aria-label': `${title} context` }), el('button', { type: 'submit', className: 'button button--secondary' }, 'Add'))); return el('section', { className: 'card huddle-card' }, el('h2', {}, title), el('p', { className: 'secondary' }, prompt), body); }
function eodTiles(completed, outstanding, record, top3) { const tiles = el('section', { className: 'eod-tiles', 'aria-label': 'End of Day overview' }); const info = [['✓','Completed',completed.length], ['→','Outstanding',outstanding.length], ['!','Risks / Critical',record?.risks?.length || 0], ['⌁','Customer / Service',record?.customerIssues?.length || 0], ['⏳','Blocked / Waiting',outstanding.filter(task => task.blocked || task.waiting).length], ['◆','Decisions',record?.decisions?.length || 0], ['↗','Handovers',record?.handovers?.length || 0], ['1·2·3',"Tomorrow's Top 3",top3.size], ['↻','Improvements',record?.improvements?.length || 0]]; info.forEach(([symbol, label, count]) => tiles.append(el('a', { className: 'eod-tile', href: `#end-of-day?section=${encodeURIComponent(label)}` }, el('span', { className: 'eod-tile-icon', 'aria-hidden': 'true' }, symbol), el('span', {}, el('strong', {}, label), el('small', {}, `${count} ${count === 1 ? 'item' : 'items'}`))))); return tiles; }
function eodSection(id, title, summary, content) { const section = el('details', { className: 'card eod-card', open: ['capture', 'outstanding', 'top3'].includes(id) }); section.append(el('summary', {}, el('span', {}, title), el('small', {}, summary)), content); return section; }
function entrySection(section, title, values = []) { const body = el('div', { className: 'stack eod-entry-body' }); if (values.length) body.append(el('ul', { className: 'eod-entry-list' }, ...values.map(item => el('li', {}, el('strong', {}, item.title), item.note ? el('span', {}, ` — ${item.note}`) : '')))); else body.append(el('p', { className: 'secondary' }, `No ${title.toLowerCase()} captured.`)); const form = el('form', { 'data-eod-entry-form': '', className: 'eod-entry-form' }, el('input', { type: 'hidden', name: 'section', value: section }), el('input', { name: 'title', maxlength: '240', required: '', placeholder: `Add ${title.toLowerCase()}…`, 'aria-label': `Add ${title}` }), el('input', { name: 'note', maxlength: '1000', placeholder: 'Optional context', 'aria-label': `${title} context` }), el('button', { type: 'submit', className: 'button button--secondary' }, 'Add')); body.append(form); return eodSection(section, title, `${values.length} captured`, body); }
function taskCheckbox(task, name, checked, attribute) { const label = el('label', { className: 'eod-task-option' }); const checkbox = el('input', { type: 'checkbox', name, value: task.id }); if (attribute) checkbox.setAttribute(attribute, ''); checkbox.checked = checked; label.append(checkbox, el('span', {}, el('strong', {}, task.title), el('small', {}, eodTaskMeta(task)))); return label; }
function taskSummary(tasks) { return el('ul', { className: 'eod-entry-list' }, ...tasks.map(task => el('li', {}, task.title, el('small', {}, ` — ${eodTaskMeta(task)}`)))); }
function formatWorkday(date) { return new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' }); }
function field(name, label, value, hint) { const wrap = el('label', { className: 'eod-field' }, el('span', {}, label), el('small', {}, hint)); const input = el('textarea', { name, rows: name === 'wins' ? '3' : '4', maxlength: '3000' }); input.value = value; wrap.append(input); return wrap; }
function eodTaskMeta(task) { return [task.dueDate ? `Due ${task.dueDate}` : 'No due date', task.blocked ? 'Blocked' : null, task.waiting ? 'Waiting' : null, task.carryCount ? `Carried ${task.carryCount}×` : null].filter(Boolean).join(' · '); }
function localDate(now = new Date()) { const offset = now.getTimezoneOffset() * 60000; return new Date(now.getTime() - offset).toISOString().slice(0, 10); }
function tasksView(tasks) { const page = el('div', { className: 'page stack' }, pageHeader('Tasks', 'Capture once. Carry forward. Complete everywhere.')); const capture = el('form', { className: 'task-capture card', 'data-task-form': '' }, el('label', { className: 'visually-hidden', for: 'task-title' }, 'New task'), el('input', { id: 'task-title', name: 'title', required: '', maxlength: '500', placeholder: 'Capture a task…' }), el('input', { name: 'dueDate', type: 'date', 'aria-label': 'Due date' }), el('button', { className: 'button button--primary', type: 'submit' }, 'Add task')); const tabs = el('nav', { className: 'task-tabs', 'aria-label': 'Task views' }); const labels = { inbox: 'Inbox', today: 'Today', upcoming: 'Upcoming', anytime: 'Anytime', someday: 'Someday', flagged: 'Flagged', urgent: 'Urgent', completed: 'Completed' }; Object.entries(labels).forEach(([key, label]) => tabs.append(el('a', { href: `#tasks?view=${key}`, className: key === getTaskView() ? 'is-active' : '' }, label))); const view = getTaskView(); const list = taskView(tasks, view); const section = el('section', { className: 'task-list', 'aria-labelledby': 'task-list-heading' }, el('h2', { id: 'task-list-heading' }, labels[view])); if (!list.length) section.append(el('p', { className: 'empty-task secondary' }, emptyCopy(view))); else list.forEach(task => section.append(taskCard(task))); page.append(capture, tabs, section); return page; }
function getTaskView() { const params = new URLSearchParams(window.location.hash.split('?')[1]); const value = params.get('view'); return ['inbox','today','upcoming','anytime','someday','flagged','urgent','completed'].includes(value) ? value : 'inbox'; }
function emptyCopy(view) { return ({ today: 'Nothing due today.', flagged: 'No flagged tasks.', urgent: 'No urgent tasks.', completed: 'Completed work will appear here.' })[view] || 'Nothing to review here yet.'; }
function taskCard(task) {
  const progress = subtaskProgress(task);
  const card = el('article', { className: `task-card ${task.status === 'completed' ? 'is-completed' : ''}` });
  const action = el('button', { className: 'task-complete', type: 'button', 'data-task-action': task.status === 'completed' ? 'reopen' : 'complete', 'data-task-id': task.id, 'aria-label': task.status === 'completed' ? `Reopen ${task.title}` : `Complete ${task.title}` }, task.status === 'completed' ? '✓' : '○');
  const content = el('div', { className: 'task-card__content' }, el('h3', {}, task.title));
  const metadata = [];
  if (task.dueDate) metadata.push(`Due ${task.dueDate}`);
  if (task.priority !== 'normal') metadata.push(`${task.priority} priority`);
  if (task.urgent) metadata.push('Urgent'); if (task.flagged) metadata.push('Flagged'); if (task.blocked) metadata.push('Blocked'); if (task.waiting) metadata.push('Waiting');
  if (metadata.length) content.append(el('p', { className: 'task-meta' }, metadata.join(' · ')));
  if (progress.total) {
    content.append(el('p', { className: 'task-progress-copy' }, `${progress.completed} of ${progress.total}`));
    content.append(el('div', { className: 'progress', role: 'progressbar', 'aria-label': 'Subtask progress', 'aria-valuemin': '0', 'aria-valuemax': String(progress.total), 'aria-valuenow': String(progress.completed) }, el('span', { style: `width:${progress.percent}%` })));
    const subs = el('div', { className: 'subtask-list' });
    task.subtasks.forEach(sub => subs.append(el('div', { className: 'subtask' }, el('button', { type: 'button', 'data-task-action': sub.completed ? 'reopen-subtask' : 'complete-subtask', 'data-task-id': task.id, 'data-subtask-id': sub.id, 'aria-label': sub.completed ? 'Reopen subtask' : 'Complete subtask' }, sub.completed ? '✓' : '○'), el('span', { className: sub.completed ? 'done' : '' }, sub.title), el('button', { type: 'button', 'data-task-action': 'delete-subtask', 'data-task-id': task.id, 'data-subtask-id': sub.id, 'aria-label': 'Delete subtask' }, '×'))));
    content.append(subs);
  }
  const actions = el('div', { className: 'task-actions' }, smallAction('edit', task, 'Details'), smallAction('add-subtask', task, 'Subtask'), smallAction('toggle-urgent', task, task.urgent ? 'Not urgent' : 'Urgent'), smallAction('toggle-flagged', task, task.flagged ? 'Unflag' : 'Flag'), smallAction('toggle-blocked', task, task.blocked ? 'Unblock' : 'Block'), smallAction('toggle-waiting', task, task.waiting ? 'Resume' : 'Waiting'));
  card.append(action, content, actions); return card;
}
function smallAction(action, task, label) { return el('button', { className: 'task-action', type: 'button', 'data-task-action': action, 'data-task-id': task.id, 'data-value': String(action === 'toggle-urgent' ? task.urgent : action === 'toggle-flagged' ? task.flagged : action === 'toggle-blocked' ? task.blocked : task.waiting) }, label); }
function dailyView() { const page = el('div', { className: 'page stack' }, pageHeader('Your Daily Leadership Playbook', 'Lead the day before the day leads you.')); const flow = el('section', { className: 'daily-flow', 'aria-labelledby': 'daily-flow-heading' }, el('div', { className: 'section-intro' }, el('p', { className: 'eyebrow' }, 'Your rhythm'), el('h2', { id: 'daily-flow-heading' }, 'Prepare. Align. Execute.'))); const tiles = el('div', { className: 'flow-grid' }); [['01', 'End of Day', 'Close today with clarity, then carry only what matters.', ROUTES.END_OF_DAY], ['02', 'Morning Huddle', 'Start aligned on people, priorities and any blockers.', ROUTES.MORNING_HUDDLE], ['03', 'Today’s Work', 'Focus your leadership attention on the next right action.', ROUTES.TODAY]].forEach(([number, title, copy, route]) => tiles.append(el('a', { className: 'flow-card', href: `#${route}` }, el('span', { className: 'flow-number' }, number), el('h3', {}, title), el('p', {}, copy), el('span', { className: 'flow-link' }, 'Open →')))); flow.append(tiles); const attention = el('section', { className: 'section', 'aria-labelledby': 'attention-heading' }, el('div', { className: 'section-heading' }, el('p', { className: 'eyebrow' }, 'At a glance'), el('h2', { id: 'attention-heading' }, 'Leadership attention'))); const grid = el('div', { className: 'attention-grid' }); [['Top 3', 'Choose the three outcomes that make today count.'], ['Risks & blockers', 'Surface obstacles before they become urgent.'], ['Outstanding actions', 'Keep ownership and follow-through visible.'], ['KPI exceptions', 'Review what needs a leadership decision.']].forEach(([title, copy]) => grid.append(emptyTile(title, copy))); attention.append(grid); page.append(flow, attention); return page; }
function settingsView() { return el('div', { className: 'page stack' }, pageHeader('Settings', 'Your data stays on this device unless you choose to export it.'), el('section', { className: 'settings-card card', 'aria-labelledby': 'backup-heading' }, el('p', { className: 'eyebrow' }, 'Local data'), el('h2', { id: 'backup-heading' }, 'Backup & restore'), el('p', { className: 'secondary' }, 'Export a portable copy of your current tasks, leadership roadmap and preferences. Import replaces the local copy only after confirmation.'), el('div', { className: 'cluster' }, el('button', { className: 'button button--primary', type: 'button', 'data-action': 'export' }, 'Export data'), el('label', { className: 'button button--secondary file-button' }, 'Import data', el('input', { type: 'file', accept: 'application/json,.json', 'data-action': 'import', className: 'visually-hidden' })))), el('section', { className: 'card settings-card' }, el('p', { className: 'eyebrow' }, 'Application'), el('h2', {}, 'TalentisOS'), el('p', { className: 'secondary' }, 'Local-first leadership workspace · Schema version 7'))); }
function placeholder(route) { const label = routeLabels[route]; return el('div', { className: 'page stack' }, pageHeader(label, dailyRoutes.includes(route) ? 'This daily workflow will be ready in its dedicated phase.' : 'This leadership tool is prepared for a later, focused phase.'), el('section', { className: 'empty-state card' }, el('div', { className: 'empty-icon', 'aria-hidden': 'true' }, '○'), el('h2', {}, 'Nothing needs your attention here yet.'), el('p', { className: 'secondary' }, 'TalentisOS is keeping this space clear until the workflow is ready to support your day.'))); }
function pageHeader(title, description) { return el('header', { className: 'page-header' }, el('p', { className: 'eyebrow' }, 'TalentisOS'), el('h1', { id: 'page-title' }, title), el('p', { className: 'page-description' }, description)); }
function emptyTile(title, copy) { return el('article', { className: 'metric-tile' }, el('h3', {}, title), el('p', {}, copy), el('span', { className: 'empty-label' }, 'Nothing to review yet')); }
function routeIcon(route) { return ({ daily: '⌂', 'end-of-day': '◐', 'morning-huddle': '☀', today: '✓', tasks: '☷', roadmap: '↗', kpis: '◫', issues: '!', meetings: '◌', improvement: '↑', playbooks: '▤', analytics: '⌁', settings: '⚙' })[route] ?? '•'; }
function icon(value) { return el('span', { className: 'nav-icon', 'aria-hidden': 'true' }, value); }
function el(tag, attributes = {}, ...children) { const node = document.createElement(tag); for (const [key, value] of Object.entries(attributes)) { if (value === undefined) continue; if (key === 'className') node.className = value; else node.setAttribute(key, value); } children.flat().forEach(child => node.append(child instanceof Node ? child : document.createTextNode(String(child)))); return node; }
