import { STORE_NAMES, createId, nowIso } from './schema.js';
import { createRecord, deleteRecord, getAllRecords, getRecord, updateRecord } from './storage.js';

const open = task => task.status === 'open';
const stamp = (task, type, metadata = {}, now = nowIso()) => ({ ...task, history: [...(task.history || []), { id: createId(), type, timestamp: now, metadata }], updatedAt: now });
const taskDate = () => new Date().toISOString().slice(0, 10);

export async function createTask(input) { const task = makeTask(input); await createRecord(STORE_NAMES.tasks, task); return task; }
export async function getTask(id) { return getRecord(STORE_NAMES.tasks, id); }
export async function listTasks() { return getAllRecords(STORE_NAMES.tasks); }
export async function updateTask(id, changes) { return mutate(id, task => stamp({ ...task, ...cleanChanges(changes) }, 'updated')); }
export async function completeTask(id) { return mutate(id, task => task.status === 'completed' ? task : stamp({ ...task, status: 'completed', completedAt: nowIso() }, 'completed')); }
export async function reopenTask(id) { return mutate(id, task => open(task) ? task : stamp({ ...task, status: 'open', completedAt: null }, 'reopened')); }
export async function deleteTask(id) { await deleteRecord(STORE_NAMES.tasks, id); }

export async function addSubtask(id, title) { return mutate(id, task => { const text = String(title || '').trim(); if (!text) throw new TypeError('A subtask title is required.'); return stamp({ ...task, subtasks: [...task.subtasks, { id: createId(), title: text, completed: false, createdAt: nowIso(), completedAt: null }] }, 'updated', { field: 'subtasks' }); }); }
export async function updateSubtask(id, subtaskId, title) { return alterSubtask(id, subtaskId, subtask => ({ ...subtask, title: requiredTitle(title) })); }
export async function completeSubtask(id, subtaskId) { return alterSubtask(id, subtaskId, subtask => subtask.completed ? subtask : { ...subtask, completed: true, completedAt: nowIso() }); }
export async function reopenSubtask(id, subtaskId) { return alterSubtask(id, subtaskId, subtask => !subtask.completed ? subtask : { ...subtask, completed: false, completedAt: null }); }
export async function deleteSubtask(id, subtaskId) { return mutate(id, task => stamp({ ...task, subtasks: task.subtasks.filter(item => item.id !== subtaskId) }, 'updated', { field: 'subtasks' })); }
export async function addTaskReference(id, reference) { return mutate(id, task => { const candidate = { id: createId(), taskId: task.id, type: reference.type, sourceId: reference.sourceId ?? null, date: reference.date ?? null, createdAt: nowIso() }; const exists = task.references.some(item => item.type === candidate.type && item.sourceId === candidate.sourceId && item.date === candidate.date); return exists ? task : stamp({ ...task, references: [...task.references, candidate] }, 'added-to-workflow', { type: candidate.type, date: candidate.date }); }); }
export async function removeTaskReference(id, referenceId) { return mutate(id, task => stamp({ ...task, references: task.references.filter(item => item.id !== referenceId) }, 'removed-from-workflow')); }
export async function carryTaskForward(id, reference) { return mutate(id, task => { const key = `${reference.type}|${reference.sourceId ?? ''}|${reference.date ?? ''}`; if (task.references.some(item => `${item.type}|${item.sourceId ?? ''}|${item.date ?? ''}` === key)) return task; const entry = { id: createId(), taskId: task.id, type: reference.type, sourceId: reference.sourceId ?? null, date: reference.date ?? null, createdAt: nowIso() }; return stamp({ ...task, references: [...task.references, entry], carryCount: task.carryCount + 1 }, 'carried', { destination: entry.type, date: entry.date }); }); }
export async function setTaskBlocked(id, blocked, reason = null) { return mutate(id, task => stamp({ ...task, blocked: Boolean(blocked), blockedReason: blocked ? String(reason || '').trim() || null : null }, blocked ? 'blocked' : 'unblocked')); }
export async function setTaskWaiting(id, waiting, waitingFor = null) { return mutate(id, task => stamp({ ...task, waiting: Boolean(waiting), waitingFor: waiting ? String(waitingFor || '').trim() || null : null }, waiting ? 'waiting' : 'resumed')); }

export function taskView(tasks, view, today = taskDate()) { const active = tasks.filter(open); const due = task => task.dueDate || ''; const matches = { inbox: task => !task.dueDate && !task.someday, today: task => due(task) <= today && due(task) !== '', upcoming: task => due(task) > today, anytime: task => !task.dueDate && !task.someday, someday: task => task.someday, flagged: task => task.flagged, urgent: task => task.urgent, completed: task => task.status === 'completed' }[view] || (() => true); return (view === 'completed' ? tasks : active).filter(matches).sort((a,b) => due(a).localeCompare(due(b)) || b.updatedAt.localeCompare(a.updatedAt)); }
export function subtaskProgress(task) { const total = task.subtasks.length; return { total, completed: task.subtasks.filter(item => item.completed).length, percent: total ? Math.round(task.subtasks.filter(item => item.completed).length / total * 100) : 0 }; }

function makeTask(input) { const title = requiredTitle(input?.title); const now = nowIso(); return { id: createId(), title, notes: String(input?.notes || ''), status: 'open', priority: input?.priority || 'normal', urgent: Boolean(input?.urgent), flagged: Boolean(input?.flagged), category: input?.category || null, tags: Array.isArray(input?.tags) ? input.tags : [], dueDate: input?.dueDate || null, dueTime: input?.dueTime || null, blocked: false, blockedReason: null, waiting: false, waitingFor: null, someday: Boolean(input?.someday), carryCount: 0, subtasks: [], references: [], history: [{ id: createId(), type: 'created', timestamp: now, metadata: {} }], createdAt: now, updatedAt: now, completedAt: null }; }
function requiredTitle(value) { const title = String(value || '').trim(); if (!title) throw new TypeError('A task title is required.'); return title; }
function cleanChanges(changes) { const value = { ...changes }; if ('title' in value) value.title = requiredTitle(value.title); if ('tags' in value && !Array.isArray(value.tags)) value.tags = []; return value; }
async function mutate(id, apply) { const stored = await getTask(id); if (!stored) throw new Error('Task not found.'); const current = { ...stored, subtasks: Array.isArray(stored.subtasks) ? stored.subtasks : [], references: Array.isArray(stored.references) ? stored.references : [], history: Array.isArray(stored.history) ? stored.history : [], carryCount: Number(stored.carryCount || 0), blockedReason: stored.blockedReason || null, waitingFor: stored.waitingFor || null, someday: Boolean(stored.someday) }; const next = apply(current); if (next === current) return current; return updateRecord(STORE_NAMES.tasks, next); }
async function alterSubtask(id, subtaskId, edit) { return mutate(id, task => { let found = false; const subtasks = task.subtasks.map(item => { if (item.id !== subtaskId) return item; found = true; return edit(item); }); if (!found) throw new Error('Subtask not found.'); return stamp({ ...task, subtasks }, 'updated', { field: 'subtasks' }); }); }
