import { STORE_NAMES, createId, nowIso } from './schema.js';
import { createRecord, deleteRecord, getAllRecords, getRecord, updateRecord } from './storage.js';

const open = task => task.status === 'open';
const stamp = (task, type, metadata = {}, now = nowIso()) => ({ ...task, history: [...(task.history || []), { id: createId(), type, timestamp: now, metadata }], updatedAt: now });
const taskDate = () => new Date().toISOString().slice(0, 10);
const REFERENCE_TYPES = new Set(['eod', 'huddle', 'today', 'meeting', 'kpi', 'issue', 'rock', 'roadmap', 'improvement', 'conversation']);

export async function createTask(input) { const task = makeTask(input); await createRecord(STORE_NAMES.tasks, task); return task; }
export async function getTask(id) { const task = await getRecord(STORE_NAMES.tasks, id); return task ? normaliseTask(task) : task; }
export async function listTasks() { return (await getAllRecords(STORE_NAMES.tasks)).filter(task => task && typeof task === 'object' && typeof task.id === 'string' && typeof task.title === 'string').map(normaliseTask); }
export async function updateTask(id, changes) { return mutate(id, task => {
  const next = { ...task, ...cleanChanges(changes) };
  const changed = Object.keys(cleanChanges(changes)).filter(key => task[key] !== next[key]);
  return changed.length ? stamp(next, historyType(changed), { fields: changed }) : task;
}); }
export async function completeTask(id) { return mutate(id, task => task.status === 'completed' ? task : stamp({ ...task, status: 'completed', completedAt: nowIso() }, 'completed')); }
export async function reopenTask(id) { return mutate(id, task => open(task) ? task : stamp({ ...task, status: 'open', completedAt: null }, 'reopened')); }
export async function deleteTask(id) { await deleteRecord(STORE_NAMES.tasks, id); }

export async function addSubtask(id, title) { return mutate(id, task => { const text = String(title || '').trim(); if (!text) throw new TypeError('A subtask title is required.'); return stamp({ ...task, subtasks: [...task.subtasks, { id: createId(), title: text, completed: false, createdAt: nowIso(), completedAt: null }] }, 'updated', { field: 'subtasks' }); }); }
export async function updateSubtask(id, subtaskId, title) { return alterSubtask(id, subtaskId, subtask => ({ ...subtask, title: requiredTitle(title) })); }
export async function completeSubtask(id, subtaskId) { return alterSubtask(id, subtaskId, subtask => subtask.completed ? subtask : { ...subtask, completed: true, completedAt: nowIso() }); }
export async function reopenSubtask(id, subtaskId) { return alterSubtask(id, subtaskId, subtask => !subtask.completed ? subtask : { ...subtask, completed: false, completedAt: null }); }
export async function deleteSubtask(id, subtaskId) { return mutate(id, task => stamp({ ...task, subtasks: task.subtasks.filter(item => item.id !== subtaskId) }, 'updated', { field: 'subtasks' })); }
export async function addTaskReference(id, reference) { return mutate(id, task => { const candidate = makeReference(task, reference); const exists = task.references.some(item => sameReference(item, candidate)); return exists ? task : stamp({ ...task, references: [...task.references, candidate] }, 'reference-added', { type: candidate.type, sourceId: candidate.sourceId, date: candidate.date }); }); }
export async function removeTaskReference(id, referenceId) { return mutate(id, task => { const reference = task.references.find(item => item.id === referenceId); return reference ? stamp({ ...task, references: task.references.filter(item => item.id !== referenceId) }, 'reference-removed', { type: reference.type, sourceId: reference.sourceId, date: reference.date }) : task; }); }
export async function carryTaskForward(id, reference) { return mutate(id, task => { const entry = makeReference(task, reference); if (task.references.some(item => sameReference(item, entry))) return task; const carry = { id: createId(), fromDate: reference.fromDate ?? null, toDate: entry.date, createdAt: nowIso() }; return stamp({ ...task, references: [...task.references, entry], carryCount: task.carryCount + 1, carryHistory: [...task.carryHistory, carry] }, 'carried-forward', { fromDate: carry.fromDate, toDate: carry.toDate, destination: entry.type }); }); }
export async function setTaskBlocked(id, blocked, reason = null) { return mutate(id, task => stamp({ ...task, blocked: Boolean(blocked), blockedReason: blocked ? String(reason || '').trim() || null : null }, blocked ? 'blocked' : 'unblocked')); }
export async function setTaskWaiting(id, waiting, waitingFor = null) { return mutate(id, task => stamp({ ...task, waiting: Boolean(waiting), waitingFor: waiting ? String(waitingFor || '').trim() || null : null }, waiting ? 'waiting' : 'resumed')); }

export function taskView(tasks, view, today = taskDate()) { const records = Array.isArray(tasks) ? tasks.map(normaliseTask) : []; const active = records.filter(open); const due = task => task.dueDate || ''; const matches = { inbox: task => !task.dueDate && !task.someday, today: task => due(task) <= today && due(task) !== '', upcoming: task => due(task) > today, anytime: task => !task.dueDate && !task.someday, someday: task => task.someday, flagged: task => task.flagged, urgent: task => task.urgent, completed: task => task.status === 'completed' }[view] || (() => true); return (view === 'completed' ? records : active).filter(matches).sort((a,b) => due(a).localeCompare(due(b)) || String(b.updatedAt || '').localeCompare(String(a.updatedAt || ''))); }
export function subtaskProgress(task) { const subtasks = Array.isArray(task?.subtasks) ? task.subtasks : []; const total = subtasks.length; const completed = subtasks.filter(item => item?.completed).length; return { total, completed, percent: total ? Math.round(completed / total * 100) : 0 }; }
export function normaliseTask(task) { return { ...task, status: task.status === 'completed' ? 'completed' : 'open', notes: String(task.notes || ''), priority: ['low', 'normal', 'high'].includes(task.priority) ? task.priority : 'normal', urgent: Boolean(task.urgent), flagged: Boolean(task.flagged), category: String(task.category || ''), tags: Array.isArray(task.tags) ? task.tags.filter(tag => typeof tag === 'string').map(tag => tag.trim()).filter(Boolean) : [], dueDate: task.dueDate || null, dueTime: task.dueTime || null, subtasks: Array.isArray(task.subtasks) ? task.subtasks.filter(item => item && typeof item === 'object').map(item => ({ ...item, completed: Boolean(item.completed), completedAt: item.completedAt || null })) : [], references: Array.isArray(task.references) ? task.references.filter(item => item && typeof item === 'object') : [], history: Array.isArray(task.history) ? task.history.filter(item => item && typeof item === 'object') : [], carryCount: Number.isFinite(Number(task.carryCount)) ? Number(task.carryCount) : 0, carryHistory: Array.isArray(task.carryHistory) ? task.carryHistory.filter(item => item && typeof item === 'object') : [], blocked: Boolean(task.blocked), blockedReason: String(task.blockedReason || ''), waiting: Boolean(task.waiting), waitingFor: String(task.waitingFor || ''), someday: Boolean(task.someday), completedAt: task.completedAt || null }; }

function makeTask(input) { const title = requiredTitle(input?.title); const now = nowIso(); return { id: createId(), title, notes: String(input?.notes || ''), status: 'open', priority: ['low', 'normal', 'high'].includes(input?.priority) ? input.priority : 'normal', urgent: Boolean(input?.urgent), flagged: Boolean(input?.flagged), category: String(input?.category || ''), tags: cleanTags(input?.tags), dueDate: input?.dueDate || null, dueTime: input?.dueTime || null, blocked: false, blockedReason: '', waiting: false, waitingFor: '', someday: Boolean(input?.someday), carryCount: 0, carryHistory: [], subtasks: [], references: [], history: [{ id: createId(), type: 'created', timestamp: now, metadata: {} }], createdAt: now, updatedAt: now, completedAt: null }; }
function requiredTitle(value) { const title = String(value || '').trim(); if (!title) throw new TypeError('A task title is required.'); return title; }
function cleanChanges(changes) { const value = { ...changes }; ['id', 'createdAt', 'updatedAt', 'completedAt', 'status', 'subtasks', 'references', 'history', 'carryCount', 'carryHistory'].forEach(key => delete value[key]); if ('title' in value) value.title = requiredTitle(value.title); if ('priority' in value && !['low', 'normal', 'high'].includes(value.priority)) value.priority = 'normal'; if ('tags' in value) value.tags = cleanTags(value.tags); if ('category' in value) value.category = String(value.category || '').trim(); if ('dueDate' in value) value.dueDate = value.dueDate || null; if ('dueTime' in value) value.dueTime = value.dueTime || null; return value; }
function cleanTags(tags) { return Array.isArray(tags) ? [...new Set(tags.filter(tag => typeof tag === 'string').map(tag => tag.trim()).filter(Boolean))] : []; }
function historyType(fields) { if (fields.includes('priority')) return 'priority-changed'; if (fields.includes('dueDate') || fields.includes('dueTime')) return 'due-date-changed'; return 'edited'; }
function makeReference(task, reference = {}) { const type = String(reference.type || '').trim(); if (!REFERENCE_TYPES.has(type)) throw new TypeError('A supported workflow reference type is required.'); return { id: createId(), taskId: task.id, type, sourceId: reference.sourceId == null ? null : String(reference.sourceId), date: reference.date || null, createdAt: nowIso() }; }
function sameReference(a, b) { return a.type === b.type && (a.sourceId ?? null) === b.sourceId && (a.date ?? null) === b.date; }
async function mutate(id, apply) { const stored = await getTask(id); if (!stored) throw new Error('Task not found.'); const current = normaliseTask(stored); const next = apply(current); if (next === current) return current; return updateRecord(STORE_NAMES.tasks, next); }
async function alterSubtask(id, subtaskId, edit) { return mutate(id, task => { let found = false; const subtasks = task.subtasks.map(item => { if (item.id !== subtaskId) return item; found = true; return edit(item); }); if (!found) throw new Error('Subtask not found.'); return stamp({ ...task, subtasks }, 'updated', { field: 'subtasks' }); }); }
