import './style.css'
import { addTasksToEod, archiveCanonicalTask, carryEodTasks, getOrCreateEod, getSettings, listTasks, quickCaptureTask, resolveEodTask, saveEod, setTaskCompleted } from './persistence/database.js'
import { dateInTimezone, nextWorkday } from './domain/workday.js'
import { registerServiceWorker } from './pwa.js'

const routes = [
  { id: 'today', label: 'Today', title: 'Today', description: 'Capture what matters, then move it forward.' },
  { id: 'prepare-tomorrow', label: 'Prepare tomorrow', title: 'Prepare tomorrow', description: 'Close today and prepare the next workday.' },
  { id: 'start-day', label: 'Start the day', title: 'Start the day', description: 'This workflow arrives in a later approved phase.' },
  { id: 'conversations', label: 'Conversations', title: 'Conversations', description: 'This workflow arrives in a later approved phase.' },
  { id: 'tasks', label: 'Tasks', title: 'Tasks', description: 'One reliable record for every commitment.' },
]
const app = document.querySelector('#app')
let settings; let tasks = []; let eod = null; let connectionCheck = 0
const escape = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c])
const route = () => routes.find((item) => item.id === (location.hash.replace('#/', '') || 'today')) || routes[0]
const today = () => dateInTimezone(new Date(), settings.leadershipWorkdayTimezone)
const relevantEodTasks = () => tasks.filter((task) => !task.archivedAt && (eod.taskIds.includes(task.id) || (task.dueDate && task.dueDate <= eod.workday) || (task.completedAt && dateInTimezone(task.completedAt, settings.leadershipWorkdayTimezone) === eod.workday)))
const taskCard = (task) => `<li class="task-card"><label><input class="task-complete" type="checkbox" data-id="${task.id}" ${task.status === 'completed' ? 'checked' : ''} aria-label="Mark ${escape(task.title)} complete" /><span class="task-title ${task.status === 'completed' ? 'is-complete' : ''}">${escape(task.title)}</span></label><div class="task-meta">${task.urgent ? '<span>Urgent</span>' : ''}${task.flagged ? '<span>Flagged</span>' : ''}${task.status === 'blocked' || task.status === 'waiting' ? `<span>${escape(task.status)}</span>` : ''}${task.dueDate ? `<span>Due ${escape(task.dueDate)}</span>` : ''}</div></li>`
function taskSurface() { const visible = tasks.filter((task) => !task.archivedAt); return `<section class="capture-panel"><div><p class="eyebrow">Quick Capture</p><h2>Add a task</h2><p>Only a title is needed. Urgency and a due date are optional.</p></div><form id="quick-capture" class="capture-form"><label>Task title<input name="title" required maxlength="240" /></label><label class="checkbox-label"><input name="urgent" type="checkbox" /> Urgent</label><label>Due date (optional)<input name="dueDate" type="date" aria-describedby="due-date-help" /></label><p id="due-date-help" class="input-help">Choose a date in the picker to save one. A displayed date is not saved until it is selected.</p><button>Add task</button><p class="form-message" role="status"></p></form></section><section class="task-workspace"><h2>Tasks</h2><ul class="task-list">${visible.map(taskCard).join('') || '<li class="empty-state">Nothing here yet. Capture the next useful action.</li>'}</ul></section>` }
function eodTask(task, readOnly = false, target = '') { const complete = task.status === 'completed'; const carried = task.carryHistory.some((entry) => entry.eodId === eod.id); return `<li class="eod-task"><div><strong class="${complete ? 'is-complete' : ''}">${escape(task.title)}</strong><p>${complete ? 'Completed' : task.status === 'blocked' || task.status === 'waiting' ? `${escape(task.status)} — ${escape(task.stateContext)}` : task.dueDate ? `Due ${escape(task.dueDate)}` : 'No due date'}${carried ? ' · prepared for the next workday' : ''}</p></div>${complete || readOnly ? '' : `<div class="eod-actions">${carried ? '' : `<label class="checkbox-label"><input type="checkbox" class="carry-select" value="${task.id}" /> Select</label><button type="button" data-carry="${task.id}">Carry to ${escape(target)}</button>`}<button type="button" data-complete="${task.id}">Complete</button><button type="button" class="text-button" data-archive="${task.id}">Archive</button></div>`}</li>` }
function eodSurface() {
  if (!eod) return '<section class="foundation-panel"><p role="status">Loading your End of Day review…</p></section>'
  const relevant = relevantEodTasks(); const outstanding = relevant.filter((task) => task.status !== 'completed'); const target = nextWorkday(eod.workday, settings.leadershipWorkdayTimezone); const isCompleted = eod.status === 'completed'; const top3 = eod.top3TaskIds.map((id) => relevant.find((task) => task.id === id)).filter(Boolean)
  const closeout = isCompleted ? `<section class="eod-section" aria-labelledby="eod-closeout-title"><h3 id="eod-closeout-title">Tomorrow’s Top 3 and closeout</h3><dl class="eod-summary"><div><dt>Top 3 for ${escape(target)}</dt><dd>${top3.map((task) => escape(task.title)).join(', ') || 'No Top 3 selected.'}</dd></div><div><dt>Recognition</dt><dd>${escape(eod.recognition) || 'None recorded.'}</dd></div><div><dt>Lesson or improvement</dt><dd>${escape(eod.lessons) || 'None recorded.'}</dd></div></dl></section>` : `<section class="eod-section"><form id="eod-closeout" class="detail-form"><h3>Tomorrow’s Top 3 and closeout</h3><p class="hint">Choose up to three existing tasks. This saves references only; it never creates task copies.</p><fieldset><legend>Top 3 for ${escape(target)}</legend>${outstanding.map((task) => `<label class="checkbox-label"><input type="checkbox" name="top3" value="${task.id}" ${eod.top3TaskIds.includes(task.id) ? 'checked' : ''} /> ${escape(task.title)}</label>`).join('') || '<p class="hint">No outstanding tasks are available for tomorrow’s Top 3.</p>'}</fieldset><label>Recognition (optional)<textarea name="recognition" maxlength="1000">${escape(eod.recognition)}</textarea></label><label>Lesson or improvement (optional)<textarea name="lessons" maxlength="1000">${escape(eod.lessons)}</textarea></label><div class="dialog-actions"><button>Save progress</button><button id="complete-eod" type="button">Complete End of Day</button></div><p class="form-message" role="status" aria-live="polite"></p></form></section>`
  return `<section class="eod-workspace"><div class="eod-heading"><div><p class="eyebrow">End of Day · ${escape(eod.workday)}</p><h2>Prepare ${escape(target)}</h2><p>${isCompleted ? 'This review is complete. You can revisit its canonical tasks.' : 'Review existing work, resolve what you can, and prepare only work that remains.'}</p></div><p class="eod-status" role="status">${isCompleted ? 'Completed' : 'In progress'}</p></div><section class="eod-section"><h3>Outstanding and current-day work</h3><p class="hint">${outstanding.length} outstanding · ${relevant.filter((task) => task.status === 'completed').length} completed</p><ul class="eod-list">${relevant.map((task) => eodTask(task, isCompleted, target)).join('') || '<li class="empty-state">No relevant tasks yet. Use Tasks to capture work once, then return here to review it.</li>'}</ul>${!isCompleted && outstanding.length ? `<div class="eod-actions"><button id="carry-selected" type="button" disabled>Carry selected to ${escape(target)}</button><button id="carry-all" type="button">Carry all outstanding to ${escape(target)}</button></div>` : ''}</section>${closeout}</section>`
}
function render() {
  const current = route(); const isTask = current.id === 'today' || current.id === 'tasks'; const isEod = current.id === 'prepare-tomorrow'; document.title = `${current.title} · TalentisOS`
  app.innerHTML = `<a class="skip-link" href="#main-content">Skip to content</a><header class="site-header"><a class="brand" href="#/today"><span class="brand-mark">T</span><span>TalentisOS</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation">☰ <span>Menu</span></button><nav id="primary-navigation" class="primary-navigation" aria-label="Core navigation"><ul>${routes.map((item) => `<li><a href="#/${item.id}" ${item.id === current.id ? 'aria-current="page"' : ''}>${item.label}</a></li>`).join('')}</ul></nav></header><main id="main-content" tabindex="-1"><section class="intro"><p class="eyebrow">Private, local workspace</p><h1>${current.title}</h1><p class="lede">${current.description}</p></section>${isTask ? taskSurface() : isEod ? eodSurface() : '<section class="foundation-panel"><p class="status-label">Foundation surface</p><h2>Kept deliberately out of scope</h2><p>This workflow is not enabled until its approved phase.</p></section>'}</main><footer class="site-footer"><p id="connection-status" role="status">Checking connection</p><p>TalentisOS keeps your information in this browser on this device.</p></footer>`
  const menu = app.querySelector('.menu-toggle'); const nav = app.querySelector('.primary-navigation'); menu.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') === 'true'; menu.setAttribute('aria-expanded', String(!open)); nav.classList.toggle('is-open', !open) }); nav.addEventListener('click', () => { menu.setAttribute('aria-expanded', 'false'); nav.classList.remove('is-open') }); if (isTask) bindTaskEvents(); if (isEod && eod?.status !== 'completed') bindEodEvents(); updateConnectionStatus()
}
async function refresh() { tasks = await listTasks({ includeArchived: true }); if (route().id === 'prepare-tomorrow') await loadEod(); render() }
async function loadEod() { eod = await getOrCreateEod(today()); const candidates = tasks.filter((task) => !task.archivedAt && ((task.dueDate && task.dueDate <= eod.workday) || (task.completedAt && dateInTimezone(task.completedAt, settings.leadershipWorkdayTimezone) === eod.workday))).map((task) => task.id); if (candidates.length) eod = await addTasksToEod(eod.id, candidates) }
function bindTaskEvents() { app.querySelector('#quick-capture').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const message = form.querySelector('.form-message'); const data = new FormData(form); const submittedDueDate = data.get('dueDate'); const dueDate = typeof submittedDueDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(submittedDueDate) ? submittedDueDate : null; try { await quickCaptureTask({ title: data.get('title'), urgent: data.get('urgent') === 'on', dueDate }); form.reset(); message.textContent = 'Task added.'; await refresh() } catch (error) { message.textContent = error.message } }); app.querySelectorAll('.task-complete').forEach((input) => input.addEventListener('change', async () => { await setTaskCompleted(input.dataset.id, input.checked); await refresh() })) }
function bindEodEvents() { const selectedCarryIds = () => [...app.querySelectorAll('.carry-select:checked')].map((input) => input.value); const carryMessage = async (ids) => { const result = await carryEodTasks(eod.id, ids); await refresh(); app.querySelector('.form-message')?.replaceChildren(`Prepared ${result.carried} task${result.carried === 1 ? '' : 's'} for ${result.targetWorkday}.`) }; app.querySelectorAll('.carry-select').forEach((input) => input.addEventListener('change', () => { app.querySelector('#carry-selected').disabled = selectedCarryIds().length === 0 })); app.querySelectorAll('[data-carry]').forEach((button) => button.addEventListener('click', async () => carryMessage([button.dataset.carry]))); app.querySelectorAll('[data-complete]').forEach((button) => button.addEventListener('click', async () => { await resolveEodTask(eod.id, button.dataset.complete, 'complete'); await refresh() })); app.querySelectorAll('[data-archive]').forEach((button) => button.addEventListener('click', async () => { await resolveEodTask(eod.id, button.dataset.archive, 'archive'); await refresh() })); app.querySelector('#carry-selected')?.addEventListener('click', async () => carryMessage(selectedCarryIds())); app.querySelector('#carry-all')?.addEventListener('click', async () => carryMessage(relevantEodTasks().filter((task) => task.status !== 'completed').map((task) => task.id))); const form = app.querySelector('#eod-closeout'); form?.addEventListener('submit', async (event) => { event.preventDefault(); await persistEod(false, form) }); app.querySelector('#complete-eod')?.addEventListener('click', async () => persistEod(true, form)) }
async function persistEod(complete, form) { const message = form.querySelector('.form-message'); try { const top3TaskIds = [...new FormData(form).getAll('top3')]; eod = await saveEod({ ...eod, taskIds: [...new Set([...eod.taskIds, ...top3TaskIds])], top3TaskIds, recognition: form.recognition.value, lessons: form.lessons.value, ...(complete ? { status: 'completed' } : {}) }); if (complete) await refresh(); else message.textContent = 'End of Day progress saved. You can safely return later.' } catch (error) { message.textContent = error.message } }
async function handleRoute() { if (route().id === 'prepare-tomorrow') { eod = null; render(); await loadEod() } render() }
async function updateConnectionStatus() { const element = app.querySelector('#connection-status'); if (!element) return; const id = ++connectionCheck; const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 3000); try { const probeUrl = new URL('./asset-manifest.json', location.href); probeUrl.searchParams.set('talentisos-connection-check', '1'); const response = await fetch(probeUrl, { cache: 'no-store', signal: controller.signal }); if (!response.ok) throw new Error(); if (id === connectionCheck) element.textContent = 'Online' } catch { if (id === connectionCheck) element.textContent = 'Offline — shell available' } finally { window.clearTimeout(timeout) } }
function renderFailure(message) { app.innerHTML = `<main class="recovery-state"><p class="eyebrow">Storage unavailable</p><h1>TalentisOS cannot safely save information here.</h1><p>${escape(message)}</p></main>` }
async function start() { if (!('indexedDB' in window)) return renderFailure('This browser does not support the local storage required by TalentisOS.'); try { settings = await getSettings(); await refresh(); window.addEventListener('hashchange', handleRoute); window.addEventListener('online', updateConnectionStatus); window.addEventListener('offline', updateConnectionStatus) } catch (error) { renderFailure('Browser storage could not be opened.'); console.error(error) } }
registerServiceWorker()
start()
