import { initializeWorkspaceStorage } from './state/storage.js';
import { createExportEnvelope, importEnvelope, parseImport } from './state/transfer.js';
import { getRoute } from './ui/router.js';
import { renderApp } from './ui/render.js';
import { addSubtask, completeTask, completeSubtask, createTask, deleteSubtask, deleteTask, getTask, listTasks, reopenTask, reopenSubtask, setTaskBlocked, setTaskWaiting, updateTask } from './state/tasks.js';
import { addEndOfDayEntry, closeEndOfDay, getEndOfDay, listEndOfDayRecords, localDate, reopenEndOfDay, saveEndOfDay, setTomorrowTop3 } from './state/end-of-day.js';
import { addCommitment, addHuddleItem, assembleMorningHuddle, completeMorningHuddle, createHuddleAction, reopenMorningHuddle, removeCommitment, removeTaskFromHuddle, setHuddleTop3 } from './state/morning-huddle.js';

const root = document.querySelector('#app');
let storageReady = false;
let startupNotice = null;
async function start() { try { await initializeWorkspaceStorage(); storageReady = true; } catch (error) { console.error('TalentisOS local storage is unavailable.', error); startupNotice = 'Local storage is unavailable. Your existing data has not been changed.'; } await render(); }
async function render() { let tasks = []; let endOfDay = null; let eodHistory = []; let huddle = null; const today = localDate(); if (storageReady) { try { [tasks, endOfDay, eodHistory, huddle] = await Promise.all([listTasks(), getEndOfDay(today), listEndOfDayRecords(), assembleMorningHuddle(today)]); } catch (error) { console.error('TalentisOS workspace could not be loaded.', error); startupNotice = 'Your workspace could not be loaded. Your data has not been changed.'; } } renderApp(root, getRoute(), tasks, endOfDay, today, eodHistory, huddle); document.querySelector('[data-action="export"]')?.addEventListener('click', exportData); document.querySelector('[data-action="import"]')?.addEventListener('change', importData); document.querySelector('[data-task-form]')?.addEventListener('submit', submitTask); document.querySelector('[data-eod-form]')?.addEventListener('submit', submitEndOfDay); root.querySelectorAll('[data-eod-entry-form]').forEach(form => form.addEventListener('submit', submitEndOfDayEntry)); root.querySelector('[data-eod-action="reopen"]')?.addEventListener('click', reopenCurrentEndOfDay); root.querySelector('[data-eod-select-all]')?.addEventListener('click', selectAllOutstanding); root.querySelectorAll('[data-top3-option]').forEach(input => input.addEventListener('change', enforceTop3)); root.querySelectorAll('[data-task-action]').forEach(button => button.addEventListener('click', taskAction)); root.querySelector('[data-huddle-top3-form]')?.addEventListener('submit', submitHuddleTop3); root.querySelector('[data-huddle-action-form]')?.addEventListener('submit', submitHuddleAction); root.querySelectorAll('[data-huddle-entry-form]').forEach(form => form.addEventListener('submit', submitHuddleEntry)); root.querySelectorAll('[data-huddle-action]').forEach(button => button.addEventListener('click', huddleAction)); if (startupNotice) { const message = startupNotice; startupNotice = null; notify(message, 'error'); } }
async function submitHuddleTop3(event) { event.preventDefault(); try { await setHuddleTop3(localDate(), new FormData(event.currentTarget).getAll('top3TaskIds')); notify("Today's Top 3 aligned."); await render(); } catch (error) { notify(error.message, 'error'); } }
async function submitHuddleAction(event) { event.preventDefault(); const values = new FormData(event.currentTarget); try { await createHuddleAction(localDate(), { title: values.get('title'), dueDate: values.get('dueDate') || null, priority: values.get('priority') }, true); notify('Canonical action added to commitments.'); await render(); } catch (error) { notify(error.message, 'error'); } }
async function submitHuddleEntry(event) { event.preventDefault(); const values = new FormData(event.currentTarget); try { await addHuddleItem(localDate(), values.get('section'), values.get('title'), values.get('note')); await render(); } catch (error) { notify(error.message, 'error'); } }
async function huddleAction(event) { const button = event.currentTarget; try { const id = button.dataset.taskId; if (button.dataset.huddleAction === 'complete') await completeTask(id); if (button.dataset.huddleAction === 'reopen-task') await reopenTask(id); if (button.dataset.huddleAction === 'commit') await addCommitment(localDate(), id); if (button.dataset.huddleAction === 'uncommit') await removeCommitment(localDate(), id); if (button.dataset.huddleAction === 'remove') await removeTaskFromHuddle(localDate(), id); if (button.dataset.huddleAction === 'complete-huddle') await completeMorningHuddle(localDate()); if (button.dataset.huddleAction === 'reopen-huddle') await reopenMorningHuddle(localDate()); await render(); } catch (error) { notify(error.message, 'error'); } }
async function submitEndOfDay(event) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const input = { date: localDate(), wins: values.get('wins'), reflection: values.get('reflection'), taskIds: values.getAll('taskIds'), top3TaskIds: values.getAll('top3TaskIds') }; try { await setTomorrowTop3(input.date, input.top3TaskIds); if (event.submitter?.value === 'close') { const record = await closeEndOfDay(input); notify(`End of Day complete. ${record.taskIds.length} task${record.taskIds.length === 1 ? '' : 's'} prepared for ${record.nextWorkday}.`); } else { await saveEndOfDay({ ...input, status: 'in-progress' }); notify('End of Day progress saved.'); } await render(); } catch (error) { notify(error.message, 'error'); } }
async function submitEndOfDayEntry(event) { event.preventDefault(); const values = new FormData(event.currentTarget); try { await addEndOfDayEntry(localDate(), values.get('section'), { title: values.get('title'), note: values.get('note') }); notify('End of Day capture saved.'); await render(); } catch (error) { notify(error.message, 'error'); } }
async function reopenCurrentEndOfDay() { try { await reopenEndOfDay(localDate()); notify('End of Day reopened for correction.'); await render(); } catch (error) { notify(error.message, 'error'); } }
function enforceTop3(event) { const selected = [...root.querySelectorAll('[data-top3-option]:checked')]; if (selected.length > 3) { event.currentTarget.checked = false; notify("Tomorrow's Top 3 is limited to three tasks.", 'error'); } }
function selectAllOutstanding() { root.querySelectorAll('input[name="taskIds"]').forEach(input => { input.checked = true; }); notify('Outstanding tasks selected. Review before completing End of Day.'); }
async function submitTask(event) { event.preventDefault(); const form = event.currentTarget; try { await createTask({ title: form.title.value, dueDate: form.dueDate.value || null }); form.reset(); await render(); } catch (error) { notify(error.message, 'error'); } }
async function taskAction(event) { const button = event.currentTarget; const id = button.dataset.taskId; try { if (button.dataset.taskAction === 'edit') return openTaskDialog(id); if (button.dataset.taskAction === 'complete') await completeTask(id); if (button.dataset.taskAction === 'reopen') await reopenTask(id); if (button.dataset.taskAction === 'toggle-urgent') await updateTask(id, { urgent: button.dataset.value !== 'true' }); if (button.dataset.taskAction === 'toggle-flagged') await updateTask(id, { flagged: button.dataset.value !== 'true' }); if (button.dataset.taskAction === 'toggle-blocked') await setTaskBlocked(id, button.dataset.value !== 'true'); if (button.dataset.taskAction === 'toggle-waiting') await setTaskWaiting(id, button.dataset.value !== 'true'); if (button.dataset.taskAction === 'add-subtask') { const title = window.prompt('Subtask title'); if (title !== null) await addSubtask(id, title); } if (button.dataset.taskAction === 'complete-subtask') await completeSubtask(id, button.dataset.subtaskId); if (button.dataset.taskAction === 'reopen-subtask') await reopenSubtask(id, button.dataset.subtaskId); if (button.dataset.taskAction === 'delete-subtask') await deleteSubtask(id, button.dataset.subtaskId); await render(); } catch (error) { notify(error.message, 'error'); } }
async function openTaskDialog(id) {
  const task = await getTask(id); if (!task) return notify('That task is no longer available.', 'error');
  const dialog = document.createElement('dialog'); dialog.className = 'dialog task-dialog';
  const form = document.createElement('form'); form.className = 'task-detail-form';
  form.innerHTML = '<header><h2>Task details</h2><p class="secondary">Keep the work item clear and actionable.</p></header>';
  const fields = [['title', 'Title', 'text'], ['notes', 'Notes', 'textarea'], ['category', 'Category', 'text'], ['tags', 'Tags (comma separated)', 'text'], ['dueDate', 'Due date', 'date'], ['dueTime', 'Due time', 'time'], ['blockedReason', 'Blocked reason', 'text'], ['waitingFor', 'Waiting for', 'text']];
  fields.forEach(([name, label, type]) => { const wrap = document.createElement('label'); wrap.textContent = label; const input = document.createElement(type === 'textarea' ? 'textarea' : 'input'); input.name = name; if (type !== 'textarea') input.type = type; input.value = name === 'tags' ? task.tags.join(', ') : task[name] || ''; if (name === 'title') { input.required = true; input.maxLength = 500; } if (name === 'notes') input.rows = 4; wrap.append(input); form.append(wrap); });
  const priority = document.createElement('label'); priority.textContent = 'Priority'; priority.innerHTML += '<select name="priority"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select>'; priority.querySelector('select').value = task.priority; form.insertBefore(priority, form.children[3]);
  const states = document.createElement('div'); states.className = 'check-grid'; ['urgent', 'flagged', 'someday', 'blocked', 'waiting'].forEach(name => { const label = document.createElement('label'); const input = document.createElement('input'); input.type = 'checkbox'; input.name = name; input.checked = task[name]; label.append(input, ` ${name[0].toUpperCase() + name.slice(1)}`); states.append(label); }); form.append(states);
  const actions = document.createElement('div'); actions.className = 'cluster'; const cancel = document.createElement('button'); cancel.type = 'button'; cancel.className = 'button button--secondary'; cancel.textContent = 'Cancel'; const save = document.createElement('button'); save.type = 'submit'; save.className = 'button button--primary'; save.textContent = 'Save changes'; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'button button--danger'; remove.textContent = 'Delete task'; actions.append(cancel, save, remove); form.append(actions); dialog.append(form);
  const close = () => { dialog.close(); dialog.remove(); }; cancel.addEventListener('click', close); dialog.addEventListener('cancel', close);
  form.addEventListener('submit', async event => { event.preventDefault(); const values = new FormData(form); try { await updateTask(id, { title: values.get('title'), notes: values.get('notes'), category: values.get('category'), tags: String(values.get('tags') || '').split(','), dueDate: values.get('dueDate'), dueTime: values.get('dueTime'), priority: values.get('priority'), urgent: values.has('urgent'), flagged: values.has('flagged'), someday: values.has('someday') }); await setTaskBlocked(id, values.has('blocked'), values.get('blockedReason')); await setTaskWaiting(id, values.has('waiting'), values.get('waitingFor')); close(); await render(); } catch (error) { notify(error.message, 'error'); } });
  remove.addEventListener('click', async () => { if (!await confirmAction('Delete this task?', 'This permanently deletes the task and its workflow references.')) return; await deleteTask(id); close(); await render(); }); document.querySelector('#dialog-layer').append(dialog); dialog.showModal();
}
async function exportData() { if (!storageReady) return notify('Local storage is unavailable. Export cannot run.', 'error'); try { const envelope = await createExportEnvelope(); const blob = new Blob([JSON.stringify(envelope, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `talentisos-backup-${envelope.exportedAt.slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); notify('Your local backup is ready.'); } catch { notify('Could not create a backup. Please try again.', 'error'); } }
async function importData(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !storageReady) return; try { const envelope = parseImport(await file.text()); if (!await confirmAction('Replace local data?', 'Replace the current local tasks and preferences with this backup? This cannot be undone.')) return; await importEnvelope(envelope); notify('Your backup has been imported.'); } catch (error) { notify(error.message || 'This backup could not be imported.', 'error'); } }
function notify(message, type = 'success') { const region = document.querySelector('#toast-region'); if (!region) return; const toast = document.createElement('p'); toast.className = `toast toast--${type}`; toast.textContent = message; region.replaceChildren(toast); window.setTimeout(() => toast.remove(), 5000); }
function confirmAction(title, message) { return new Promise(resolve => { const layer = document.querySelector('#dialog-layer'); const dialog = document.createElement('dialog'); dialog.className = 'dialog'; const heading = document.createElement('h2'); heading.textContent = title; const copy = document.createElement('p'); copy.className = 'secondary'; copy.textContent = message; const actions = document.createElement('div'); actions.className = 'cluster'; const cancel = document.createElement('button'); cancel.className = 'button button--secondary'; cancel.type = 'button'; cancel.textContent = 'Cancel'; const confirm = document.createElement('button'); const deleting = title.startsWith('Delete'); confirm.className = deleting ? 'button button--danger' : 'button button--primary'; confirm.type = 'button'; confirm.textContent = deleting ? 'Delete task' : 'Replace data'; actions.append(cancel, confirm); dialog.append(heading, copy, actions); const finish = value => { dialog.close(); dialog.remove(); resolve(value); }; cancel.addEventListener('click', () => finish(false)); confirm.addEventListener('click', () => finish(true)); dialog.addEventListener('cancel', () => finish(false)); layer.append(dialog); dialog.showModal(); }); }
window.addEventListener('hashchange', () => { render().catch(error => console.error(error)); }); start();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(error => console.warn('Service worker registration failed.', error)));
